import { GetLoadBalancerLoads } from "../definitions/GetLoadBalancerLoads";
import { GetLoadBalancerLoadsResponse } from "../definitions/GetLoadBalancerLoadsResponse";
import { GetLoadBalancerRuleStatistics } from "../definitions/GetLoadBalancerRuleStatistics";
import { GetLoadBalancerRuleStatisticsResponse } from "../definitions/GetLoadBalancerRuleStatisticsResponse";
import { SetEnqueueLoadBalancerPowerOff } from "../definitions/SetEnqueueLoadBalancerPowerOff";
import { SetEnqueueLoadBalancerPowerOffResponse } from "../definitions/SetEnqueueLoadBalancerPowerOffResponse";
import { GetLoadBalancerNotifications } from "../definitions/GetLoadBalancerNotifications";
import { GetLoadBalancerNotificationsResponse } from "../definitions/GetLoadBalancerNotificationsResponse";
import { SetEnqueueLoadBalancerStart } from "../definitions/SetEnqueueLoadBalancerStart";
import { SetEnqueueLoadBalancerStartResponse } from "../definitions/SetEnqueueLoadBalancerStartResponse";
import { SetAddLoadBalancerContacts } from "../definitions/SetAddLoadBalancerContacts";
import { SetAddLoadBalancerContactsResponse } from "../definitions/SetAddLoadBalancerContactsResponse";
import { SetRemoveLoadBalancerContacts } from "../definitions/SetRemoveLoadBalancerContacts";
import { SetRemoveLoadBalancerContactsResponse } from "../definitions/SetRemoveLoadBalancerContactsResponse";
import { SetEnqueueLoadBalancerAddInstances } from "../definitions/SetEnqueueLoadBalancerAddInstances";
import { SetEnqueueLoadBalancerAddInstancesResponse } from "../definitions/SetEnqueueLoadBalancerAddInstancesResponse";
import { SetEnqueueLoadBalancerRemoveInstances } from "../definitions/SetEnqueueLoadBalancerRemoveInstances";
import { SetEnqueueLoadBalancerRemoveInstancesResponse } from "../definitions/SetEnqueueLoadBalancerRemoveInstancesResponse";
import { SetModifyLoadBalancer } from "../definitions/SetModifyLoadBalancer";
import { SetModifyLoadBalancerResponse } from "../definitions/SetModifyLoadBalancerResponse";
import { SetAddLoadBalancerRule } from "../definitions/SetAddLoadBalancerRule";
import { SetAddLoadBalancerRuleResponse } from "../definitions/SetAddLoadBalancerRuleResponse";
import { SetRemoveLoadBalancerRule } from "../definitions/SetRemoveLoadBalancerRule";
import { SetRemoveLoadBalancerRuleResponse } from "../definitions/SetRemoveLoadBalancerRuleResponse";
import { IWsEndUserSetEnqueueReinitializeLoadBalancerOutputMessage1 } from "../definitions/IWsEndUserSetEnqueueReinitializeLoadBalancerOutputMessage1";
import { GetPreConfiguredPackages } from "../definitions/GetPreConfiguredPackages";
import { GetPreConfiguredPackagesResponse } from "../definitions/GetPreConfiguredPackagesResponse";
import { IWsEndUserGetAdditionalIpServicesOutputMessage1 } from "../definitions/IWsEndUserGetAdditionalIpServicesOutputMessage1";
import { SetEnqueueReinitializeServer } from "../definitions/SetEnqueueReinitializeServer";
import { SetEnqueueReinitializeServerResponse } from "../definitions/SetEnqueueReinitializeServerResponse";
import { GetAllCloudIpAddresses } from "../definitions/GetAllCloudIpAddresses";
import { GetAllCloudIpAddressesResponse } from "../definitions/GetAllCloudIpAddressesResponse";
import { SetEnqueueSetReverseDns } from "../definitions/SetEnqueueSetReverseDns";
import { SetEnqueueSetReverseDnsResponse } from "../definitions/SetEnqueueSetReverseDnsResponse";
import { SetEnqueueResetReverseDns } from "../definitions/SetEnqueueResetReverseDns";
import { SetEnqueueResetReverseDnsResponse } from "../definitions/SetEnqueueResetReverseDnsResponse";
import { GetReverseDns } from "../definitions/GetReverseDns";
import { GetReverseDnsResponse } from "../definitions/GetReverseDnsResponse";
import { IWsEndUserIsLuckySmartAvailableOutputMessage1 } from "../definitions/IWsEndUserIsLuckySmartAvailableOutputMessage1";
import { IWsEndUserGetLastSoldOutSettingItemListOutputMessage1 } from "../definitions/IWsEndUserGetLastSoldOutSettingItemListOutputMessage1";
import { IWsEndUserGetHybridLinksOutputMessage1 } from "../definitions/IWsEndUserGetHybridLinksOutputMessage1";
import { IWsEndUserGetHybridLinksPricingTypesOutputMessage1 } from "../definitions/IWsEndUserGetHybridLinksPricingTypesOutputMessage1";
import { IWsEndUserSetEnqueueCreateHybridLinkOutputMessage1 } from "../definitions/IWsEndUserSetEnqueueCreateHybridLinkOutputMessage1";
import { IWsEndUserSetEnqueueDeleteHybridLinkOutputMessage1 } from "../definitions/IWsEndUserSetEnqueueDeleteHybridLinkOutputMessage1";
import { IWsEndUserGetPurchasedPrivateCloudsBaseOutputMessage1 } from "../definitions/IWsEndUserGetPurchasedPrivateCloudsBaseOutputMessage1";
import { IWsEndUserGetCountriesOutputMessage1 } from "../definitions/IWsEndUserGetCountriesOutputMessage1";
import { IWsEndUserGetSharedStoragePricingTypesOutputMessage1 } from "../definitions/IWsEndUserGetSharedStoragePricingTypesOutputMessage1";
import { IWsEndUserGetSharedStorageDetailsOutputMessage1 } from "../definitions/IWsEndUserGetSharedStorageDetailsOutputMessage1";
import { IWsEndUserRenameHybridLinkOutputMessage1 } from "../definitions/IWsEndUserRenameHybridLinkOutputMessage1";
import { IWsEndUserPlannedChangePrivateCloudWindowsLicenseDeletionOutputMessage1 } from "../definitions/IWsEndUserPlannedChangePrivateCloudWindowsLicenseDeletionOutputMessage1";
import { IWsEndUserPlannedChangePrivateCloudLicenseDeletionOutputMessage1 } from "../definitions/IWsEndUserPlannedChangePrivateCloudLicenseDeletionOutputMessage1";
import { IWsEndUserChangePrivateCloudPasswordOutputMessage1 } from "../definitions/IWsEndUserChangePrivateCloudPasswordOutputMessage1";
import { IWsEndUserChangeZertoPasswordOutputMessage1 } from "../definitions/IWsEndUserChangeZertoPasswordOutputMessage1";
import { IWsEndUserGetVirtualMachinePricingTypesOutputMessage1 } from "../definitions/IWsEndUserGetVirtualMachinePricingTypesOutputMessage1";
import { IWsEndUserSetEnqueueModifyVirtualMachinePackageOutputMessage1 } from "../definitions/IWsEndUserSetEnqueueModifyVirtualMachinePackageOutputMessage1";
import { IWsEndUserServerPlannedChangeDeletionOutputMessage1 } from "../definitions/IWsEndUserServerPlannedChangeDeletionOutputMessage1";
import { IWsEndUserGetHypervisorTemplatesPriorityOutputMessage1 } from "../definitions/IWsEndUserGetHypervisorTemplatesPriorityOutputMessage1";
import { IWsEndUserGetHypervisorTemplatesOutputMessage1 } from "../definitions/IWsEndUserGetHypervisorTemplatesOutputMessage1";
import { IWsEndUserGetHypervisorTemplateDetailsOutputMessage1 } from "../definitions/IWsEndUserGetHypervisorTemplateDetailsOutputMessage1";
import { IWsEndUserGetPrivateCloudPricingTypesOutputMessage1 } from "../definitions/IWsEndUserGetPrivateCloudPricingTypesOutputMessage1";
import { IWsEndUserGetPrivateCloudResourcesOutputMessage1 } from "../definitions/IWsEndUserGetPrivateCloudResourcesOutputMessage1";
import { IWsEndUserGetPrivateCloudCustomProductsOutputMessage1 } from "../definitions/IWsEndUserGetPrivateCloudCustomProductsOutputMessage1";
import { IWsEndUserGetPublicVLanForUserOutputMessage1 } from "../definitions/IWsEndUserGetPublicVLanForUserOutputMessage1";
import { IWsEndUserManageIpOutputMessage1 } from "../definitions/IWsEndUserManageIpOutputMessage1";
import { IWsEndUserGetPrivateCloudNamingBlacklistsOutputMessage1 } from "../definitions/IWsEndUserGetPrivateCloudNamingBlacklistsOutputMessage1";
import { IWsEndUserCancelDeleteVirtualMachineOutputMessage1 } from "../definitions/IWsEndUserCancelDeleteVirtualMachineOutputMessage1";
import { IWsEndUserCreateVpcUserOutputMessage1 } from "../definitions/IWsEndUserCreateVpcUserOutputMessage1";
import { IWsEndUserGetVpcUsersOutputMessage1 } from "../definitions/IWsEndUserGetVpcUsersOutputMessage1";
import { IWsEndUserRequestVpcUserOtpTokenOutputMessage1 } from "../definitions/IWsEndUserRequestVpcUserOtpTokenOutputMessage1";
import { IWsEndUserSetVpcOtpStatusOutputMessage1 } from "../definitions/IWsEndUserSetVpcOtpStatusOutputMessage1";
import { IWsEndUserResetVpcUserPasswordOutputMessage1 } from "../definitions/IWsEndUserResetVpcUserPasswordOutputMessage1";
import { IWsEndUserDeleteVpcUserOutputMessage1 } from "../definitions/IWsEndUserDeleteVpcUserOutputMessage1";
import { IWsEndUserVerifyVpcUserOtpOutputMessage1 } from "../definitions/IWsEndUserVerifyVpcUserOtpOutputMessage1";
import { IWsEndUserGetVpcRolesOutputMessage1 } from "../definitions/IWsEndUserGetVpcRolesOutputMessage1";
import { IWsEndUserUpdateVpcUserOutputMessage1 } from "../definitions/IWsEndUserUpdateVpcUserOutputMessage1";
import { IWsEndUserSyncVpcUserOtpTokenOutputMessage1 } from "../definitions/IWsEndUserSyncVpcUserOtpTokenOutputMessage1";
import { IWsEndUserRemoveOldIpFromVpsOutputMessage1 } from "../definitions/IWsEndUserRemoveOldIpFromVpsOutputMessage1";
import { GetUserAuthenticationToken } from "../definitions/GetUserAuthenticationToken";
import { GetUserAuthenticationTokenResponse } from "../definitions/GetUserAuthenticationTokenResponse";
import { GetCompanyByUrl } from "../definitions/GetCompanyByUrl";
import { GetCompanyByUrlResponse } from "../definitions/GetCompanyByUrlResponse";
import { GetHypervisorTypes } from "../definitions/GetHypervisorTypes";
import { GetHypervisorTypesResponse } from "../definitions/GetHypervisorTypesResponse";
import { GetHypervisors } from "../definitions/GetHypervisors";
import { GetHypervisorsResponse } from "../definitions/GetHypervisorsResponse";
import { IWsEndUserGetApplianceTypesOutputMessage1 } from "../definitions/IWsEndUserGetApplianceTypesOutputMessage1";
import { IWsEndUserGetAllTagsOutputMessage1 } from "../definitions/IWsEndUserGetAllTagsOutputMessage1";
import { GetHypervisorDetails } from "../definitions/GetHypervisorDetails";
import { GetHypervisorDetailsResponse } from "../definitions/GetHypervisorDetailsResponse";
import { GetVirtualDatacenter } from "../definitions/GetVirtualDatacenter";
import { GetVirtualDatacenterResponse } from "../definitions/GetVirtualDatacenterResponse";
import { GetVirtualDatacenterCost } from "../definitions/GetVirtualDatacenterCost";
import { GetVirtualDatacenterCostResponse } from "../definitions/GetVirtualDatacenterCostResponse";
import { GetServers } from "../definitions/GetServers";
import { GetServersResponse } from "../definitions/GetServersResponse";
import { IWsEndUserGetServersListOutputMessage1 } from "../definitions/IWsEndUserGetServersListOutputMessage1";
import { IWsEndUserGetPagedServersListOutputMessage1 } from "../definitions/IWsEndUserGetPagedServersListOutputMessage1";
import { GetServerDetails } from "../definitions/GetServerDetails";
import { GetServerDetailsResponse } from "../definitions/GetServerDetailsResponse";
import { GetCredit } from "../definitions/GetCredit";
import { GetCreditResponse } from "../definitions/GetCreditResponse";
import { GetPriceList } from "../definitions/GetPriceList";
import { GetPriceListResponse } from "../definitions/GetPriceListResponse";
import { GetPurchasedVLans } from "../definitions/GetPurchasedVLans";
import { GetPurchasedVLansResponse } from "../definitions/GetPurchasedVLansResponse";
import { GetPurchasedIpAddresses } from "../definitions/GetPurchasedIpAddresses";
import { GetPurchasedIpAddressesResponse } from "../definitions/GetPurchasedIpAddressesResponse";
import { IWsEndUserGetOpenStackFlavorsOutputMessage1 } from "../definitions/IWsEndUserGetOpenStackFlavorsOutputMessage1";
import { GetJobs } from "../definitions/GetJobs";
import { GetJobsResponse } from "../definitions/GetJobsResponse";
import { GetLogs } from "../definitions/GetLogs";
import { GetLogsResponse } from "../definitions/GetLogsResponse";
import { IWsEndUserGetOperationsLogOutputMessage1 } from "../definitions/IWsEndUserGetOperationsLogOutputMessage1";
import { GetDatacenterConfigurations } from "../definitions/GetDatacenterConfigurations";
import { GetDatacenterConfigurationsResponse } from "../definitions/GetDatacenterConfigurationsResponse";
import { GetCustomVirtualDisks } from "../definitions/GetCustomVirtualDisks";
import { GetCustomVirtualDisksResponse } from "../definitions/GetCustomVirtualDisksResponse";
import { GetIsos } from "../definitions/GetIsos";
import { GetIsosResponse } from "../definitions/GetIsosResponse";
import { GetUserInfo } from "../definitions/GetUserInfo";
import { GetUserInfoResponse } from "../definitions/GetUserInfoResponse";
import { GetPurchasedFtp1 } from "../definitions/GetPurchasedFtp1";
import { GetPurchasedFtpResponse1 } from "../definitions/GetPurchasedFtpResponse1";
import { GetNews } from "../definitions/GetNews";
import { GetNewsResponse } from "../definitions/GetNewsResponse";
import { GetScheduledOperations } from "../definitions/GetScheduledOperations";
import { GetScheduledOperationsResponse } from "../definitions/GetScheduledOperationsResponse";
import { GetServerSchedulesLogs } from "../definitions/GetServerSchedulesLogs";
import { GetServerSchedulesLogsResponse } from "../definitions/GetServerSchedulesLogsResponse";
import { GetSchedulerDataTypes } from "../definitions/GetSchedulerDataTypes";
import { GetSchedulerDataTypesResponse } from "../definitions/GetSchedulerDataTypesResponse";
import { GetTemplateDetails } from "../definitions/GetTemplateDetails";
import { GetTemplateDetailsResponse } from "../definitions/GetTemplateDetailsResponse";
import { GetTemplateCategories } from "../definitions/GetTemplateCategories";
import { GetTemplateCategoriesResponse } from "../definitions/GetTemplateCategoriesResponse";
import { IWsEndUserGetTemplateLicensesOutputMessage1 } from "../definitions/IWsEndUserGetTemplateLicensesOutputMessage1";
import { GetAvailablePersonalTemplates } from "../definitions/GetAvailablePersonalTemplates";
import { GetAvailablePersonalTemplatesResponse } from "../definitions/GetAvailablePersonalTemplatesResponse";
import { GetSystemStatusHistory } from "../definitions/GetSystemStatusHistory";
import { GetSystemStatusHistoryResponse } from "../definitions/GetSystemStatusHistoryResponse";
import { GetSharedStorages } from "../definitions/GetSharedStorages";
import { GetSharedStoragesResponse } from "../definitions/GetSharedStoragesResponse";
import { GetAdditionalServices } from "../definitions/GetAdditionalServices";
import { GetAdditionalServicesResponse } from "../definitions/GetAdditionalServicesResponse";
import { GetPurchasedAdditionalServices } from "../definitions/GetPurchasedAdditionalServices";
import { GetPurchasedAdditionalServicesResponse } from "../definitions/GetPurchasedAdditionalServicesResponse";
import { GetRemoteAccessUrl } from "../definitions/GetRemoteAccessUrl";
import { GetRemoteAccessUrlResponse } from "../definitions/GetRemoteAccessUrlResponse";
import { IWsEndUserGetRemoteAccessUrlExOutputMessage1 } from "../definitions/IWsEndUserGetRemoteAccessUrlExOutputMessage1";
import { IWsEndUserGetRemoteAccessUrlAsyncResponseOutputMessage1 } from "../definitions/IWsEndUserGetRemoteAccessUrlAsyncResponseOutputMessage1";
import { IWsEndUserGetVmPerformanceOutputMessage1 } from "../definitions/IWsEndUserGetVmPerformanceOutputMessage1";
import { IWsEndUserGetVmPerformancesOutputMessage1 } from "../definitions/IWsEndUserGetVmPerformancesOutputMessage1";
import { IWsEndUserGetVmMetricsOutputMessage1 } from "../definitions/IWsEndUserGetVmMetricsOutputMessage1";
import { IWsEndUserGetVirtualMachineCostOutputMessage1 } from "../definitions/IWsEndUserGetVirtualMachineCostOutputMessage1";
import { IWsEndUserGetVirtualMachineResourcesProductsOutputMessage1 } from "../definitions/IWsEndUserGetVirtualMachineResourcesProductsOutputMessage1";
import { CheckEnqueueServerCreation } from "../definitions/CheckEnqueueServerCreation";
import { CheckEnqueueServerCreationResponse } from "../definitions/CheckEnqueueServerCreationResponse";
import { SetEnqueueServerCreation } from "../definitions/SetEnqueueServerCreation";
import { SetEnqueueServerCreationResponse } from "../definitions/SetEnqueueServerCreationResponse";
import { IWsEndUserSetEnqueueServerCreationExOutputMessage1 } from "../definitions/IWsEndUserSetEnqueueServerCreationExOutputMessage1";
import { SetEnqueueServerUpdate } from "../definitions/SetEnqueueServerUpdate";
import { SetEnqueueServerUpdateResponse } from "../definitions/SetEnqueueServerUpdateResponse";
import { SetEnqueueServerStart } from "../definitions/SetEnqueueServerStart";
import { SetEnqueueServerStartResponse } from "../definitions/SetEnqueueServerStartResponse";
import { SetEnqueueServerStop } from "../definitions/SetEnqueueServerStop";
import { SetEnqueueServerStopResponse } from "../definitions/SetEnqueueServerStopResponse";
import { SetEnqueueServerDeletion } from "../definitions/SetEnqueueServerDeletion";
import { SetEnqueueServerDeletionResponse } from "../definitions/SetEnqueueServerDeletionResponse";
import { SetEnqueueServerReset } from "../definitions/SetEnqueueServerReset";
import { SetEnqueueServerResetResponse } from "../definitions/SetEnqueueServerResetResponse";
import { SetEnqueueServerRestart } from "../definitions/SetEnqueueServerRestart";
import { SetEnqueueServerRestartResponse } from "../definitions/SetEnqueueServerRestartResponse";
import { SetEnqueueServerPowerOff } from "../definitions/SetEnqueueServerPowerOff";
import { SetEnqueueServerPowerOffResponse } from "../definitions/SetEnqueueServerPowerOffResponse";
import { SetEnqueueServerArchiviation } from "../definitions/SetEnqueueServerArchiviation";
import { SetEnqueueServerArchiviationResponse } from "../definitions/SetEnqueueServerArchiviationResponse";
import { SetEnqueueServerRestore } from "../definitions/SetEnqueueServerRestore";
import { SetEnqueueServerRestoreResponse } from "../definitions/SetEnqueueServerRestoreResponse";
import { SetRenameServer } from "../definitions/SetRenameServer";
import { SetRenameServerResponse } from "../definitions/SetRenameServerResponse";
import { SetEnqueueMountDvdIso } from "../definitions/SetEnqueueMountDvdIso";
import { SetEnqueueMountDvdIsoResponse } from "../definitions/SetEnqueueMountDvdIsoResponse";
import { SetEnqueueUnmountDvdIso } from "../definitions/SetEnqueueUnmountDvdIso";
import { SetEnqueueUnmountDvdIsoResponse } from "../definitions/SetEnqueueUnmountDvdIsoResponse";
import { SetEnqueueVirtualDiskExport } from "../definitions/SetEnqueueVirtualDiskExport";
import { SetEnqueueVirtualDiskExportResponse } from "../definitions/SetEnqueueVirtualDiskExportResponse";
import { SetEnqueueVirtualDiskManage } from "../definitions/SetEnqueueVirtualDiskManage";
import { SetEnqueueVirtualDiskManageResponse } from "../definitions/SetEnqueueVirtualDiskManageResponse";
import { SetEnqueueServerSnapshot } from "../definitions/SetEnqueueServerSnapshot";
import { SetEnqueueServerSnapshotResponse } from "../definitions/SetEnqueueServerSnapshotResponse";
import { SetEnqueuePersonalTemplateCreation } from "../definitions/SetEnqueuePersonalTemplateCreation";
import { SetEnqueuePersonalTemplateCreationResponse } from "../definitions/SetEnqueuePersonalTemplateCreationResponse";
import { SetChangeNoteServer } from "../definitions/SetChangeNoteServer";
import { SetChangeNoteServerResponse } from "../definitions/SetChangeNoteServerResponse";
import { SetPurchaseIpAddress } from "../definitions/SetPurchaseIpAddress";
import { SetPurchaseIpAddressResponse } from "../definitions/SetPurchaseIpAddressResponse";
import { SetRemoveIpAddress } from "../definitions/SetRemoveIpAddress";
import { SetRemoveIpAddressResponse } from "../definitions/SetRemoveIpAddressResponse";
import { SetEnqueueAssociateIpAddress } from "../definitions/SetEnqueueAssociateIpAddress";
import { SetEnqueueAssociateIpAddressResponse } from "../definitions/SetEnqueueAssociateIpAddressResponse";
import { SetEnqueueDeassociateIpAddress } from "../definitions/SetEnqueueDeassociateIpAddress";
import { SetEnqueueDeassociateIpAddressResponse } from "../definitions/SetEnqueueDeassociateIpAddressResponse";
import { SetPurchaseVLan } from "../definitions/SetPurchaseVLan";
import { SetPurchaseVLanResponse } from "../definitions/SetPurchaseVLanResponse";
import { SetRemoveVLan } from "../definitions/SetRemoveVLan";
import { SetRemoveVLanResponse } from "../definitions/SetRemoveVLanResponse";
import { SetRenameVLan } from "../definitions/SetRenameVLan";
import { SetRenameVLanResponse } from "../definitions/SetRenameVLanResponse";
import { SetEnqueueAssociateVLan } from "../definitions/SetEnqueueAssociateVLan";
import { SetEnqueueAssociateVLanResponse } from "../definitions/SetEnqueueAssociateVLanResponse";
import { SetEnqueueDeassociateVLan } from "../definitions/SetEnqueueDeassociateVLan";
import { SetEnqueueDeassociateVLanResponse } from "../definitions/SetEnqueueDeassociateVLanResponse";
import { SetEnqueueCreateFtpAccount1 } from "../definitions/SetEnqueueCreateFtpAccount1";
import { SetEnqueueCreateFtpAccountResponse1 } from "../definitions/SetEnqueueCreateFtpAccountResponse1";
import { SetEnqueueResizeFtpAccount1 } from "../definitions/SetEnqueueResizeFtpAccount1";
import { SetEnqueueResizeFtpAccountResponse1 } from "../definitions/SetEnqueueResizeFtpAccountResponse1";
import { SetReadNews } from "../definitions/SetReadNews";
import { SetReadNewsResponse } from "../definitions/SetReadNewsResponse";
import { SetAddServerScheduledOperation } from "../definitions/SetAddServerScheduledOperation";
import { SetAddServerScheduledOperationResponse } from "../definitions/SetAddServerScheduledOperationResponse";
import { SetUpdateServerScheduledOperation } from "../definitions/SetUpdateServerScheduledOperation";
import { SetUpdateServerScheduledOperationResponse } from "../definitions/SetUpdateServerScheduledOperationResponse";
import { SetRemoveServerScheduledOperation } from "../definitions/SetRemoveServerScheduledOperation";
import { SetRemoveServerScheduledOperationResponse } from "../definitions/SetRemoveServerScheduledOperationResponse";
import { SetEnqueuePurchaseSharedStorage } from "../definitions/SetEnqueuePurchaseSharedStorage";
import { SetEnqueuePurchaseSharedStorageResponse } from "../definitions/SetEnqueuePurchaseSharedStorageResponse";
import { SetEnqueueRemoveSharedStorage } from "../definitions/SetEnqueueRemoveSharedStorage";
import { SetEnqueueRemoveSharedStorageResponse } from "../definitions/SetEnqueueRemoveSharedStorageResponse";
import { SetEnqueueModifySharedStorage } from "../definitions/SetEnqueueModifySharedStorage";
import { SetEnqueueModifySharedStorageResponse } from "../definitions/SetEnqueueModifySharedStorageResponse";
import { SetEnqueueAddIqnSharedStorage1 } from "../definitions/SetEnqueueAddIqnSharedStorage1";
import { SetEnqueueAddIqnSharedStorageResponse1 } from "../definitions/SetEnqueueAddIqnSharedStorageResponse1";
import { SetEnqueueRemoveIqnSharedStorage1 } from "../definitions/SetEnqueueRemoveIqnSharedStorage1";
import { SetEnqueueRemoveIqnSharedStorageResponse1 } from "../definitions/SetEnqueueRemoveIqnSharedStorageResponse1";
import { SetRenameSharedStorage } from "../definitions/SetRenameSharedStorage";
import { SetRenameSharedStorageResponse } from "../definitions/SetRenameSharedStorageResponse";
import { SetUpdatePersonalTemplate } from "../definitions/SetUpdatePersonalTemplate";
import { SetUpdatePersonalTemplateResponse } from "../definitions/SetUpdatePersonalTemplateResponse";
import { SetRemovePersonalTemplate } from "../definitions/SetRemovePersonalTemplate";
import { SetRemovePersonalTemplateResponse } from "../definitions/SetRemovePersonalTemplateResponse";
import { SetPurchasedAdditionalServices } from "../definitions/SetPurchasedAdditionalServices";
import { SetPurchasedAdditionalServicesResponse } from "../definitions/SetPurchasedAdditionalServicesResponse";
import { SetControlToolActive } from "../definitions/SetControlToolActive";
import { SetControlToolActiveResponse } from "../definitions/SetControlToolActiveResponse";
import { SetControlToolDisable } from "../definitions/SetControlToolDisable";
import { SetControlToolDisableResponse } from "../definitions/SetControlToolDisableResponse";
import { GetControlToolCheck } from "../definitions/GetControlToolCheck";
import { GetControlToolCheckResponse } from "../definitions/GetControlToolCheckResponse";
import { GetControlToolActivationRequests } from "../definitions/GetControlToolActivationRequests";
import { GetControlToolActivationRequestsResponse } from "../definitions/GetControlToolActivationRequestsResponse";
import { SetControlToolActivationRequest } from "../definitions/SetControlToolActivationRequest";
import { SetControlToolActivationRequestResponse } from "../definitions/SetControlToolActivationRequestResponse";
import { GetNetworkAdapterConfiguration } from "../definitions/GetNetworkAdapterConfiguration";
import { GetNetworkAdapterConfigurationResponse } from "../definitions/GetNetworkAdapterConfigurationResponse";
import { GetControlToolCommandResult } from "../definitions/GetControlToolCommandResult";
import { GetControlToolCommandResultResponse } from "../definitions/GetControlToolCommandResultResponse";
import { SetEnqueueUpdateControlTool } from "../definitions/SetEnqueueUpdateControlTool";
import { SetEnqueueUpdateControlToolResponse } from "../definitions/SetEnqueueUpdateControlToolResponse";
import { GetScheduleOccurrences } from "../definitions/GetScheduleOccurrences";
import { GetScheduleOccurrencesResponse } from "../definitions/GetScheduleOccurrencesResponse";
import { GetVdcGraph1 } from "../definitions/GetVdcGraph1";
import { GetVdcGraphResponse1 } from "../definitions/GetVdcGraphResponse1";
import { SetAddVdcGraph1 } from "../definitions/SetAddVdcGraph1";
import { SetAddVdcGraphResponse1 } from "../definitions/SetAddVdcGraphResponse1";
import { SetUpdateVdcGraph1 } from "../definitions/SetUpdateVdcGraph1";
import { SetUpdateVdcGraphResponse1 } from "../definitions/SetUpdateVdcGraphResponse1";
import { GetAssistanceLanguages } from "../definitions/GetAssistanceLanguages";
import { GetAssistanceLanguagesResponse } from "../definitions/GetAssistanceLanguagesResponse";
import { GetAssistanceLanguagesList } from "../definitions/GetAssistanceLanguagesList";
import { GetAssistanceLanguagesListResponse } from "../definitions/GetAssistanceLanguagesListResponse";
import { SetUpdateAssistanceRequest } from "../definitions/SetUpdateAssistanceRequest";
import { SetUpdateAssistanceRequestResponse } from "../definitions/SetUpdateAssistanceRequestResponse";
import { GetAssistanceRequestDetails } from "../definitions/GetAssistanceRequestDetails";
import { GetAssistanceRequestDetailsResponse } from "../definitions/GetAssistanceRequestDetailsResponse";
import { SetAssistanceQuotationAcceptance } from "../definitions/SetAssistanceQuotationAcceptance";
import { SetAssistanceQuotationAcceptanceResponse } from "../definitions/SetAssistanceQuotationAcceptanceResponse";
import { SetSendAssistanceRequest } from "../definitions/SetSendAssistanceRequest";
import { SetSendAssistanceRequestResponse } from "../definitions/SetSendAssistanceRequestResponse";
import { SetInsertAssistanceRequest } from "../definitions/SetInsertAssistanceRequest";
import { SetInsertAssistanceRequestResponse } from "../definitions/SetInsertAssistanceRequestResponse";
import { GetUserAssistanceRequests } from "../definitions/GetUserAssistanceRequests";
import { GetUserAssistanceRequestsResponse } from "../definitions/GetUserAssistanceRequestsResponse";
import { IWsEndUserSetEnqueuePurchasePrivateCloudOutputMessage1 } from "../definitions/IWsEndUserSetEnqueuePurchasePrivateCloudOutputMessage1";
import { IWsEndUserGetPrivateCloudResourcesTypesOutputMessage1 } from "../definitions/IWsEndUserGetPrivateCloudResourcesTypesOutputMessage1";
import { IWsEndUserGetPrivateCloudResourcesTypes2OutputMessage1 } from "../definitions/IWsEndUserGetPrivateCloudResourcesTypes2OutputMessage1";
import { IWsEndUserGetPurchasedPrivateCloudsOutputMessage1 } from "../definitions/IWsEndUserGetPurchasedPrivateCloudsOutputMessage1";
import { IWsEndUserGetPurchasedPrivateCloudDetailsOutputMessage1 } from "../definitions/IWsEndUserGetPurchasedPrivateCloudDetailsOutputMessage1";
import { IWsEndUserGetPurchasedPrivateCloudDetails2OutputMessage1 } from "../definitions/IWsEndUserGetPurchasedPrivateCloudDetails2OutputMessage1";
import { IWsEndUserSetEnqueueModifyPrivateCloudResourcesOutputMessage1 } from "../definitions/IWsEndUserSetEnqueueModifyPrivateCloudResourcesOutputMessage1";
import { IWsEndUserSetEnqueuePrivateCloudDeletionOutputMessage1 } from "../definitions/IWsEndUserSetEnqueuePrivateCloudDeletionOutputMessage1";
import { IWsEndUserCancelDeletePrivateCloudInstanceOutputMessage1 } from "../definitions/IWsEndUserCancelDeletePrivateCloudInstanceOutputMessage1";
import { IWsEndUserSetEnqueuePrivateCloudActivationOutputMessage1 } from "../definitions/IWsEndUserSetEnqueuePrivateCloudActivationOutputMessage1";
import { IWsEndUserGetPrivateCloudOrganizationsOutputMessage1 } from "../definitions/IWsEndUserGetPrivateCloudOrganizationsOutputMessage1";
import { IWsEndUserGetPrivateCloudOrganizationDetailsOutputMessage1 } from "../definitions/IWsEndUserGetPrivateCloudOrganizationDetailsOutputMessage1";
import { IWsEndUserGetHybridLinksbyOrgOutputMessage1 } from "../definitions/IWsEndUserGetHybridLinksbyOrgOutputMessage1";
import { IWsEndUserGetActivatedPrivateCloudFeaturesOutputMessage1 } from "../definitions/IWsEndUserGetActivatedPrivateCloudFeaturesOutputMessage1";
import { IWsEndUserSetEnqueueModifyPrivateCloudOrganizationOutputMessage1 } from "../definitions/IWsEndUserSetEnqueueModifyPrivateCloudOrganizationOutputMessage1";
import { SetEnqueueLoadBalancerCreation } from "../definitions/SetEnqueueLoadBalancerCreation";
import { SetEnqueueLoadBalancerCreationResponse } from "../definitions/SetEnqueueLoadBalancerCreationResponse";
import { SetEnqueueLoadBalancerDeletion } from "../definitions/SetEnqueueLoadBalancerDeletion";
import { SetEnqueueLoadBalancerDeletionResponse } from "../definitions/SetEnqueueLoadBalancerDeletionResponse";
import { GetLoadBalancers } from "../definitions/GetLoadBalancers";
import { GetLoadBalancersResponse } from "../definitions/GetLoadBalancersResponse";

export interface BasicHttpsEndpoint {
    GetLoadBalancerLoads(getLoadBalancerLoads: GetLoadBalancerLoads, callback: (err: any, result: GetLoadBalancerLoadsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetLoadBalancerRuleStatistics(getLoadBalancerRuleStatistics: GetLoadBalancerRuleStatistics, callback: (err: any, result: GetLoadBalancerRuleStatisticsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueLoadBalancerPowerOff(setEnqueueLoadBalancerPowerOff: SetEnqueueLoadBalancerPowerOff, callback: (err: any, result: SetEnqueueLoadBalancerPowerOffResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetLoadBalancerNotifications(getLoadBalancerNotifications: GetLoadBalancerNotifications, callback: (err: any, result: GetLoadBalancerNotificationsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueLoadBalancerStart(setEnqueueLoadBalancerStart: SetEnqueueLoadBalancerStart, callback: (err: any, result: SetEnqueueLoadBalancerStartResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetAddLoadBalancerContacts(setAddLoadBalancerContacts: SetAddLoadBalancerContacts, callback: (err: any, result: SetAddLoadBalancerContactsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRemoveLoadBalancerContacts(setRemoveLoadBalancerContacts: SetRemoveLoadBalancerContacts, callback: (err: any, result: SetRemoveLoadBalancerContactsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueLoadBalancerAddInstances(setEnqueueLoadBalancerAddInstances: SetEnqueueLoadBalancerAddInstances, callback: (err: any, result: SetEnqueueLoadBalancerAddInstancesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueLoadBalancerRemoveInstances(setEnqueueLoadBalancerRemoveInstances: SetEnqueueLoadBalancerRemoveInstances, callback: (err: any, result: SetEnqueueLoadBalancerRemoveInstancesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetModifyLoadBalancer(setModifyLoadBalancer: SetModifyLoadBalancer, callback: (err: any, result: SetModifyLoadBalancerResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetAddLoadBalancerRule(setAddLoadBalancerRule: SetAddLoadBalancerRule, callback: (err: any, result: SetAddLoadBalancerRuleResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRemoveLoadBalancerRule(setRemoveLoadBalancerRule: SetRemoveLoadBalancerRule, callback: (err: any, result: SetRemoveLoadBalancerRuleResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueReinitializeLoadBalancer(iWsEndUserSetEnqueueReinitializeLoadBalancerInputMessage: {}, callback: (err: any, result: IWsEndUserSetEnqueueReinitializeLoadBalancerOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPreConfiguredPackages(getPreConfiguredPackages: GetPreConfiguredPackages, callback: (err: any, result: GetPreConfiguredPackagesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAdditionalIPServices(iWsEndUserGetAdditionalIpServicesInputMessage: {}, callback: (err: any, result: IWsEndUserGetAdditionalIpServicesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueReinitializeServer(setEnqueueReinitializeServer: SetEnqueueReinitializeServer, callback: (err: any, result: SetEnqueueReinitializeServerResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAllCloudIpAddresses(getAllCloudIpAddresses: GetAllCloudIpAddresses, callback: (err: any, result: GetAllCloudIpAddressesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueSetReverseDns(setEnqueueSetReverseDns: SetEnqueueSetReverseDns, callback: (err: any, result: SetEnqueueSetReverseDnsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueResetReverseDns(setEnqueueResetReverseDns: SetEnqueueResetReverseDns, callback: (err: any, result: SetEnqueueResetReverseDnsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetReverseDns(getReverseDns: GetReverseDns, callback: (err: any, result: GetReverseDnsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    IsLuckySmartAvailable(iWsEndUserIsLuckySmartAvailableInputMessage: {}, callback: (err: any, result: IWsEndUserIsLuckySmartAvailableOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetLastSoldOutSettingItemList(iWsEndUserGetLastSoldOutSettingItemListInputMessage: {}, callback: (err: any, result: IWsEndUserGetLastSoldOutSettingItemListOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHybridLinks(iWsEndUserGetHybridLinksInputMessage: {}, callback: (err: any, result: IWsEndUserGetHybridLinksOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHybridLinksPricingTypes(iWsEndUserGetHybridLinksPricingTypesInputMessage: {}, callback: (err: any, result: IWsEndUserGetHybridLinksPricingTypesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueCreateHybridLink(iWsEndUserSetEnqueueCreateHybridLinkInputMessage: {}, callback: (err: any, result: IWsEndUserSetEnqueueCreateHybridLinkOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueDeleteHybridLink(iWsEndUserSetEnqueueDeleteHybridLinkInputMessage: {}, callback: (err: any, result: IWsEndUserSetEnqueueDeleteHybridLinkOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedPrivateCloudsBase(iWsEndUserGetPurchasedPrivateCloudsBaseInputMessage: {}, callback: (err: any, result: IWsEndUserGetPurchasedPrivateCloudsBaseOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetCountries(iWsEndUserGetCountriesInputMessage: {}, callback: (err: any, result: IWsEndUserGetCountriesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSharedStoragePricingTypes(iWsEndUserGetSharedStoragePricingTypesInputMessage: {}, callback: (err: any, result: IWsEndUserGetSharedStoragePricingTypesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSharedStorageDetails(iWsEndUserGetSharedStorageDetailsInputMessage: {}, callback: (err: any, result: IWsEndUserGetSharedStorageDetailsOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    RenameHybridLink(iWsEndUserRenameHybridLinkInputMessage: {}, callback: (err: any, result: IWsEndUserRenameHybridLinkOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    PlannedChangePrivateCloudWindowsLicenseDeletion(iWsEndUserPlannedChangePrivateCloudWindowsLicenseDeletionInputMessage: {}, callback: (err: any, result: IWsEndUserPlannedChangePrivateCloudWindowsLicenseDeletionOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    PlannedChangePrivateCloudLicenseDeletion(iWsEndUserPlannedChangePrivateCloudLicenseDeletionInputMessage: {}, callback: (err: any, result: IWsEndUserPlannedChangePrivateCloudLicenseDeletionOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ChangePrivateCloudPassword(iWsEndUserChangePrivateCloudPasswordInputMessage: {}, callback: (err: any, result: IWsEndUserChangePrivateCloudPasswordOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ChangeZertoPassword(iWsEndUserChangeZertoPasswordInputMessage: {}, callback: (err: any, result: IWsEndUserChangeZertoPasswordOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVirtualMachinePricingTypes(iWsEndUserGetVirtualMachinePricingTypesInputMessage: {}, callback: (err: any, result: IWsEndUserGetVirtualMachinePricingTypesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueModifyVirtualMachinePackage(iWsEndUserSetEnqueueModifyVirtualMachinePackageInputMessage: {}, callback: (err: any, result: IWsEndUserSetEnqueueModifyVirtualMachinePackageOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ServerPlannedChangeDeletion(iWsEndUserServerPlannedChangeDeletionInputMessage: {}, callback: (err: any, result: IWsEndUserServerPlannedChangeDeletionOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHypervisorTemplatesPriority(iWsEndUserGetHypervisorTemplatesPriorityInputMessage: {}, callback: (err: any, result: IWsEndUserGetHypervisorTemplatesPriorityOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHypervisorTemplates(iWsEndUserGetHypervisorTemplatesInputMessage: {}, callback: (err: any, result: IWsEndUserGetHypervisorTemplatesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHypervisorTemplateDetails(iWsEndUserGetHypervisorTemplateDetailsInputMessage: {}, callback: (err: any, result: IWsEndUserGetHypervisorTemplateDetailsOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudPricingTypes(iWsEndUserGetPrivateCloudPricingTypesInputMessage: {}, callback: (err: any, result: IWsEndUserGetPrivateCloudPricingTypesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudResources(iWsEndUserGetPrivateCloudResourcesInputMessage: {}, callback: (err: any, result: IWsEndUserGetPrivateCloudResourcesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudCustomProducts(iWsEndUserGetPrivateCloudCustomProductsInputMessage: {}, callback: (err: any, result: IWsEndUserGetPrivateCloudCustomProductsOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPublicVLanForUser(iWsEndUserGetPublicVLanForUserInputMessage: {}, callback: (err: any, result: IWsEndUserGetPublicVLanForUserOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ManageIP(iWsEndUserManageIpInputMessage: {}, callback: (err: any, result: IWsEndUserManageIpOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudNamingBlacklists(iWsEndUserGetPrivateCloudNamingBlacklistsInputMessage: {}, callback: (err: any, result: IWsEndUserGetPrivateCloudNamingBlacklistsOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CancelDeleteVirtualMachine(iWsEndUserCancelDeleteVirtualMachineInputMessage: {}, callback: (err: any, result: IWsEndUserCancelDeleteVirtualMachineOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateVPCUser(iWsEndUserCreateVpcUserInputMessage: {}, callback: (err: any, result: IWsEndUserCreateVpcUserOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVPCUsers(iWsEndUserGetVpcUsersInputMessage: {}, callback: (err: any, result: IWsEndUserGetVpcUsersOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    RequestVPCUserOtpToken(iWsEndUserRequestVpcUserOtpTokenInputMessage: {}, callback: (err: any, result: IWsEndUserRequestVpcUserOtpTokenOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetVPCOtpStatus(iWsEndUserSetVpcOtpStatusInputMessage: {}, callback: (err: any, result: IWsEndUserSetVpcOtpStatusOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ResetVPCUserPassword(iWsEndUserResetVpcUserPasswordInputMessage: {}, callback: (err: any, result: IWsEndUserResetVpcUserPasswordOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    DeleteVPCUser(iWsEndUserDeleteVpcUserInputMessage: {}, callback: (err: any, result: IWsEndUserDeleteVpcUserOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    VerifyVPCUserOtp(iWsEndUserVerifyVpcUserOtpInputMessage: {}, callback: (err: any, result: IWsEndUserVerifyVpcUserOtpOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVPCRoles(iWsEndUserGetVpcRolesInputMessage: {}, callback: (err: any, result: IWsEndUserGetVpcRolesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    UpdateVPCUser(iWsEndUserUpdateVpcUserInputMessage: {}, callback: (err: any, result: IWsEndUserUpdateVpcUserOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SyncVPCUserOtpToken(iWsEndUserSyncVpcUserOtpTokenInputMessage: {}, callback: (err: any, result: IWsEndUserSyncVpcUserOtpTokenOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    RemoveOldIpFromVPS(iWsEndUserRemoveOldIpFromVpsInputMessage: {}, callback: (err: any, result: IWsEndUserRemoveOldIpFromVpsOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetUserAuthenticationToken(getUserAuthenticationToken: GetUserAuthenticationToken, callback: (err: any, result: GetUserAuthenticationTokenResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetCompanyByUrl(getCompanyByUrl: GetCompanyByUrl, callback: (err: any, result: GetCompanyByUrlResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHypervisorTypes(getHypervisorTypes: GetHypervisorTypes, callback: (err: any, result: GetHypervisorTypesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHypervisors(getHypervisors: GetHypervisors, callback: (err: any, result: GetHypervisorsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetApplianceTypes(iWsEndUserGetApplianceTypesInputMessage: {}, callback: (err: any, result: IWsEndUserGetApplianceTypesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAllTags(iWsEndUserGetAllTagsInputMessage: {}, callback: (err: any, result: IWsEndUserGetAllTagsOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHypervisorDetails(getHypervisorDetails: GetHypervisorDetails, callback: (err: any, result: GetHypervisorDetailsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVirtualDatacenter(getVirtualDatacenter: GetVirtualDatacenter, callback: (err: any, result: GetVirtualDatacenterResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVirtualDatacenterCost(getVirtualDatacenterCost: GetVirtualDatacenterCost, callback: (err: any, result: GetVirtualDatacenterCostResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetServers(getServers: GetServers, callback: (err: any, result: GetServersResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetServersList(iWsEndUserGetServersListInputMessage: {}, callback: (err: any, result: IWsEndUserGetServersListOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPagedServersList(iWsEndUserGetPagedServersListInputMessage: {}, callback: (err: any, result: IWsEndUserGetPagedServersListOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetServerDetails(getServerDetails: GetServerDetails, callback: (err: any, result: GetServerDetailsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetCredit(getCredit: GetCredit, callback: (err: any, result: GetCreditResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPriceList(getPriceList: GetPriceList, callback: (err: any, result: GetPriceListResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedVLans(getPurchasedVLans: GetPurchasedVLans, callback: (err: any, result: GetPurchasedVLansResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedIpAddresses(getPurchasedIpAddresses: GetPurchasedIpAddresses, callback: (err: any, result: GetPurchasedIpAddressesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOpenStackFlavors(iWsEndUserGetOpenStackFlavorsInputMessage: {}, callback: (err: any, result: IWsEndUserGetOpenStackFlavorsOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetJobs(getJobs: GetJobs, callback: (err: any, result: GetJobsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetLogs(getLogs: GetLogs, callback: (err: any, result: GetLogsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOperationsLog(iWsEndUserGetOperationsLogInputMessage: {}, callback: (err: any, result: IWsEndUserGetOperationsLogOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetDatacenterConfigurations(getDatacenterConfigurations: GetDatacenterConfigurations, callback: (err: any, result: GetDatacenterConfigurationsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetCustomVirtualDisks(getCustomVirtualDisks: GetCustomVirtualDisks, callback: (err: any, result: GetCustomVirtualDisksResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetIsos(getIsos: GetIsos, callback: (err: any, result: GetIsosResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetUserInfo(getUserInfo: GetUserInfo, callback: (err: any, result: GetUserInfoResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedFTP(getPurchasedFtp: GetPurchasedFtp1, callback: (err: any, result: GetPurchasedFtpResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetNews(getNews: GetNews, callback: (err: any, result: GetNewsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetScheduledOperations(getScheduledOperations: GetScheduledOperations, callback: (err: any, result: GetScheduledOperationsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetServerSchedulesLogs(getServerSchedulesLogs: GetServerSchedulesLogs, callback: (err: any, result: GetServerSchedulesLogsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSchedulerDataTypes(getSchedulerDataTypes: GetSchedulerDataTypes, callback: (err: any, result: GetSchedulerDataTypesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetTemplateDetails(getTemplateDetails: GetTemplateDetails, callback: (err: any, result: GetTemplateDetailsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetTemplateCategories(getTemplateCategories: GetTemplateCategories, callback: (err: any, result: GetTemplateCategoriesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetTemplateLicenses(iWsEndUserGetTemplateLicensesInputMessage: {}, callback: (err: any, result: IWsEndUserGetTemplateLicensesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAvailablePersonalTemplates(getAvailablePersonalTemplates: GetAvailablePersonalTemplates, callback: (err: any, result: GetAvailablePersonalTemplatesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSystemStatusHistory(getSystemStatusHistory: GetSystemStatusHistory, callback: (err: any, result: GetSystemStatusHistoryResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSharedStorages(getSharedStorages: GetSharedStorages, callback: (err: any, result: GetSharedStoragesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAdditionalServices(getAdditionalServices: GetAdditionalServices, callback: (err: any, result: GetAdditionalServicesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedAdditionalServices(getPurchasedAdditionalServices: GetPurchasedAdditionalServices, callback: (err: any, result: GetPurchasedAdditionalServicesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetRemoteAccessUrl(getRemoteAccessUrl: GetRemoteAccessUrl, callback: (err: any, result: GetRemoteAccessUrlResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetRemoteAccessUrlEx(iWsEndUserGetRemoteAccessUrlExInputMessage: {}, callback: (err: any, result: IWsEndUserGetRemoteAccessUrlExOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetRemoteAccessUrlAsyncResponse(iWsEndUserGetRemoteAccessUrlAsyncResponseInputMessage: {}, callback: (err: any, result: IWsEndUserGetRemoteAccessUrlAsyncResponseOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVMPerformance(iWsEndUserGetVmPerformanceInputMessage: {}, callback: (err: any, result: IWsEndUserGetVmPerformanceOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVMPerformances(iWsEndUserGetVmPerformancesInputMessage: {}, callback: (err: any, result: IWsEndUserGetVmPerformancesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVMMetrics(iWsEndUserGetVmMetricsInputMessage: {}, callback: (err: any, result: IWsEndUserGetVmMetricsOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVirtualMachineCost(iWsEndUserGetVirtualMachineCostInputMessage: {}, callback: (err: any, result: IWsEndUserGetVirtualMachineCostOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVirtualMachineResourcesProducts(iWsEndUserGetVirtualMachineResourcesProductsInputMessage: {}, callback: (err: any, result: IWsEndUserGetVirtualMachineResourcesProductsOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CheckEnqueueServerCreation(checkEnqueueServerCreation: CheckEnqueueServerCreation, callback: (err: any, result: CheckEnqueueServerCreationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerCreation(setEnqueueServerCreation: SetEnqueueServerCreation, callback: (err: any, result: SetEnqueueServerCreationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerCreationEx(iWsEndUserSetEnqueueServerCreationExInputMessage: {}, callback: (err: any, result: IWsEndUserSetEnqueueServerCreationExOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerUpdate(setEnqueueServerUpdate: SetEnqueueServerUpdate, callback: (err: any, result: SetEnqueueServerUpdateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerStart(setEnqueueServerStart: SetEnqueueServerStart, callback: (err: any, result: SetEnqueueServerStartResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerStop(setEnqueueServerStop: SetEnqueueServerStop, callback: (err: any, result: SetEnqueueServerStopResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerDeletion(setEnqueueServerDeletion: SetEnqueueServerDeletion, callback: (err: any, result: SetEnqueueServerDeletionResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerReset(setEnqueueServerReset: SetEnqueueServerReset, callback: (err: any, result: SetEnqueueServerResetResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerRestart(setEnqueueServerRestart: SetEnqueueServerRestart, callback: (err: any, result: SetEnqueueServerRestartResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerPowerOff(setEnqueueServerPowerOff: SetEnqueueServerPowerOff, callback: (err: any, result: SetEnqueueServerPowerOffResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerArchiviation(setEnqueueServerArchiviation: SetEnqueueServerArchiviation, callback: (err: any, result: SetEnqueueServerArchiviationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerRestore(setEnqueueServerRestore: SetEnqueueServerRestore, callback: (err: any, result: SetEnqueueServerRestoreResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRenameServer(setRenameServer: SetRenameServer, callback: (err: any, result: SetRenameServerResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueMountDvdIso(setEnqueueMountDvdIso: SetEnqueueMountDvdIso, callback: (err: any, result: SetEnqueueMountDvdIsoResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueUnmountDvdIso(setEnqueueUnmountDvdIso: SetEnqueueUnmountDvdIso, callback: (err: any, result: SetEnqueueUnmountDvdIsoResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueVirtualDiskExport(setEnqueueVirtualDiskExport: SetEnqueueVirtualDiskExport, callback: (err: any, result: SetEnqueueVirtualDiskExportResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueVirtualDiskManage(setEnqueueVirtualDiskManage: SetEnqueueVirtualDiskManage, callback: (err: any, result: SetEnqueueVirtualDiskManageResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerSnapshot(setEnqueueServerSnapshot: SetEnqueueServerSnapshot, callback: (err: any, result: SetEnqueueServerSnapshotResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueuePersonalTemplateCreation(setEnqueuePersonalTemplateCreation: SetEnqueuePersonalTemplateCreation, callback: (err: any, result: SetEnqueuePersonalTemplateCreationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetChangeNoteServer(setChangeNoteServer: SetChangeNoteServer, callback: (err: any, result: SetChangeNoteServerResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetPurchaseIpAddress(setPurchaseIpAddress: SetPurchaseIpAddress, callback: (err: any, result: SetPurchaseIpAddressResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRemoveIpAddress(setRemoveIpAddress: SetRemoveIpAddress, callback: (err: any, result: SetRemoveIpAddressResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueAssociateIpAddress(setEnqueueAssociateIpAddress: SetEnqueueAssociateIpAddress, callback: (err: any, result: SetEnqueueAssociateIpAddressResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueDeassociateIpAddress(setEnqueueDeassociateIpAddress: SetEnqueueDeassociateIpAddress, callback: (err: any, result: SetEnqueueDeassociateIpAddressResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetPurchaseVLan(setPurchaseVLan: SetPurchaseVLan, callback: (err: any, result: SetPurchaseVLanResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRemoveVLan(setRemoveVLan: SetRemoveVLan, callback: (err: any, result: SetRemoveVLanResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRenameVLan(setRenameVLan: SetRenameVLan, callback: (err: any, result: SetRenameVLanResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueAssociateVLan(setEnqueueAssociateVLan: SetEnqueueAssociateVLan, callback: (err: any, result: SetEnqueueAssociateVLanResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueDeassociateVLan(setEnqueueDeassociateVLan: SetEnqueueDeassociateVLan, callback: (err: any, result: SetEnqueueDeassociateVLanResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueCreateFTPAccount(setEnqueueCreateFtpAccount: SetEnqueueCreateFtpAccount1, callback: (err: any, result: SetEnqueueCreateFtpAccountResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueResizeFTPAccount(setEnqueueResizeFtpAccount: SetEnqueueResizeFtpAccount1, callback: (err: any, result: SetEnqueueResizeFtpAccountResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetReadNews(setReadNews: SetReadNews, callback: (err: any, result: SetReadNewsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetAddServerScheduledOperation(setAddServerScheduledOperation: SetAddServerScheduledOperation, callback: (err: any, result: SetAddServerScheduledOperationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetUpdateServerScheduledOperation(setUpdateServerScheduledOperation: SetUpdateServerScheduledOperation, callback: (err: any, result: SetUpdateServerScheduledOperationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRemoveServerScheduledOperation(setRemoveServerScheduledOperation: SetRemoveServerScheduledOperation, callback: (err: any, result: SetRemoveServerScheduledOperationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueuePurchaseSharedStorage(setEnqueuePurchaseSharedStorage: SetEnqueuePurchaseSharedStorage, callback: (err: any, result: SetEnqueuePurchaseSharedStorageResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueRemoveSharedStorage(setEnqueueRemoveSharedStorage: SetEnqueueRemoveSharedStorage, callback: (err: any, result: SetEnqueueRemoveSharedStorageResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueModifySharedStorage(setEnqueueModifySharedStorage: SetEnqueueModifySharedStorage, callback: (err: any, result: SetEnqueueModifySharedStorageResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueAddIQNSharedStorage(setEnqueueAddIqnSharedStorage: SetEnqueueAddIqnSharedStorage1, callback: (err: any, result: SetEnqueueAddIqnSharedStorageResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueRemoveIQNSharedStorage(setEnqueueRemoveIqnSharedStorage: SetEnqueueRemoveIqnSharedStorage1, callback: (err: any, result: SetEnqueueRemoveIqnSharedStorageResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRenameSharedStorage(setRenameSharedStorage: SetRenameSharedStorage, callback: (err: any, result: SetRenameSharedStorageResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetUpdatePersonalTemplate(setUpdatePersonalTemplate: SetUpdatePersonalTemplate, callback: (err: any, result: SetUpdatePersonalTemplateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRemovePersonalTemplate(setRemovePersonalTemplate: SetRemovePersonalTemplate, callback: (err: any, result: SetRemovePersonalTemplateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetPurchasedAdditionalServices(setPurchasedAdditionalServices: SetPurchasedAdditionalServices, callback: (err: any, result: SetPurchasedAdditionalServicesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetControlToolActive(setControlToolActive: SetControlToolActive, callback: (err: any, result: SetControlToolActiveResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetControlToolDisable(setControlToolDisable: SetControlToolDisable, callback: (err: any, result: SetControlToolDisableResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetControlToolCheck(getControlToolCheck: GetControlToolCheck, callback: (err: any, result: GetControlToolCheckResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetControlToolActivationRequests(getControlToolActivationRequests: GetControlToolActivationRequests, callback: (err: any, result: GetControlToolActivationRequestsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetControlToolActivationRequest(setControlToolActivationRequest: SetControlToolActivationRequest, callback: (err: any, result: SetControlToolActivationRequestResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetNetworkAdapterConfiguration(getNetworkAdapterConfiguration: GetNetworkAdapterConfiguration, callback: (err: any, result: GetNetworkAdapterConfigurationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetControlToolCommandResult(getControlToolCommandResult: GetControlToolCommandResult, callback: (err: any, result: GetControlToolCommandResultResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueUpdateControlTool(setEnqueueUpdateControlTool: SetEnqueueUpdateControlTool, callback: (err: any, result: SetEnqueueUpdateControlToolResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetScheduleOccurrences(getScheduleOccurrences: GetScheduleOccurrences, callback: (err: any, result: GetScheduleOccurrencesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVDCGraph(getVdcGraph: GetVdcGraph1, callback: (err: any, result: GetVdcGraphResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetAddVDCGraph(setAddVdcGraph: SetAddVdcGraph1, callback: (err: any, result: SetAddVdcGraphResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetUpdateVDCGraph(setUpdateVdcGraph: SetUpdateVdcGraph1, callback: (err: any, result: SetUpdateVdcGraphResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAssistanceLanguages(getAssistanceLanguages: GetAssistanceLanguages, callback: (err: any, result: GetAssistanceLanguagesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAssistanceLanguagesList(getAssistanceLanguagesList: GetAssistanceLanguagesList, callback: (err: any, result: GetAssistanceLanguagesListResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetUpdateAssistanceRequest(setUpdateAssistanceRequest: SetUpdateAssistanceRequest, callback: (err: any, result: SetUpdateAssistanceRequestResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAssistanceRequestDetails(getAssistanceRequestDetails: GetAssistanceRequestDetails, callback: (err: any, result: GetAssistanceRequestDetailsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetAssistanceQuotationAcceptance(setAssistanceQuotationAcceptance: SetAssistanceQuotationAcceptance, callback: (err: any, result: SetAssistanceQuotationAcceptanceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetSendAssistanceRequest(setSendAssistanceRequest: SetSendAssistanceRequest, callback: (err: any, result: SetSendAssistanceRequestResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetInsertAssistanceRequest(setInsertAssistanceRequest: SetInsertAssistanceRequest, callback: (err: any, result: SetInsertAssistanceRequestResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetUserAssistanceRequests(getUserAssistanceRequests: GetUserAssistanceRequests, callback: (err: any, result: GetUserAssistanceRequestsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueuePurchasePrivateCloud(iWsEndUserSetEnqueuePurchasePrivateCloudInputMessage: {}, callback: (err: any, result: IWsEndUserSetEnqueuePurchasePrivateCloudOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudResourcesTypes(iWsEndUserGetPrivateCloudResourcesTypesInputMessage: {}, callback: (err: any, result: IWsEndUserGetPrivateCloudResourcesTypesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudResourcesTypes2(iWsEndUserGetPrivateCloudResourcesTypes2InputMessage: {}, callback: (err: any, result: IWsEndUserGetPrivateCloudResourcesTypes2OutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedPrivateClouds(iWsEndUserGetPurchasedPrivateCloudsInputMessage: {}, callback: (err: any, result: IWsEndUserGetPurchasedPrivateCloudsOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedPrivateCloudDetails(iWsEndUserGetPurchasedPrivateCloudDetailsInputMessage: {}, callback: (err: any, result: IWsEndUserGetPurchasedPrivateCloudDetailsOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedPrivateCloudDetails2(iWsEndUserGetPurchasedPrivateCloudDetails2InputMessage: {}, callback: (err: any, result: IWsEndUserGetPurchasedPrivateCloudDetails2OutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueModifyPrivateCloudResources(iWsEndUserSetEnqueueModifyPrivateCloudResourcesInputMessage: {}, callback: (err: any, result: IWsEndUserSetEnqueueModifyPrivateCloudResourcesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueuePrivateCloudDeletion(iWsEndUserSetEnqueuePrivateCloudDeletionInputMessage: {}, callback: (err: any, result: IWsEndUserSetEnqueuePrivateCloudDeletionOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CancelDeletePrivateCloudInstance(iWsEndUserCancelDeletePrivateCloudInstanceInputMessage: {}, callback: (err: any, result: IWsEndUserCancelDeletePrivateCloudInstanceOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueuePrivateCloudActivation(iWsEndUserSetEnqueuePrivateCloudActivationInputMessage: {}, callback: (err: any, result: IWsEndUserSetEnqueuePrivateCloudActivationOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudOrganizations(iWsEndUserGetPrivateCloudOrganizationsInputMessage: {}, callback: (err: any, result: IWsEndUserGetPrivateCloudOrganizationsOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudOrganizationDetails(iWsEndUserGetPrivateCloudOrganizationDetailsInputMessage: {}, callback: (err: any, result: IWsEndUserGetPrivateCloudOrganizationDetailsOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHybridLinksbyOrg(iWsEndUserGetHybridLinksbyOrgInputMessage: {}, callback: (err: any, result: IWsEndUserGetHybridLinksbyOrgOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetActivatedPrivateCloudFeatures(iWsEndUserGetActivatedPrivateCloudFeaturesInputMessage: {}, callback: (err: any, result: IWsEndUserGetActivatedPrivateCloudFeaturesOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueModifyPrivateCloudOrganization(iWsEndUserSetEnqueueModifyPrivateCloudOrganizationInputMessage: {}, callback: (err: any, result: IWsEndUserSetEnqueueModifyPrivateCloudOrganizationOutputMessage1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueLoadBalancerCreation(setEnqueueLoadBalancerCreation: SetEnqueueLoadBalancerCreation, callback: (err: any, result: SetEnqueueLoadBalancerCreationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueLoadBalancerDeletion(setEnqueueLoadBalancerDeletion: SetEnqueueLoadBalancerDeletion, callback: (err: any, result: SetEnqueueLoadBalancerDeletionResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetLoadBalancers(getLoadBalancers: GetLoadBalancers, callback: (err: any, result: GetLoadBalancersResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
}
