import { GetLoadBalancerLoads } from "../definitions/GetLoadBalancerLoads";
import { GetLoadBalancerLoadsResponse } from "../definitions/GetLoadBalancerLoadsResponse";
import { GetLoadBalancerRuleStatistics } from "../definitions/GetLoadBalancerRuleStatistics";
import { GetLoadBalancerRuleStatisticsResponse } from "../definitions/GetLoadBalancerRuleStatisticsResponse";
import { SetEnqueueLoadBalancerPowerOff } from "../definitions/SetEnqueueLoadBalancerPowerOff";
import { SetEnqueueLoadBalancerPowerOffResponse } from "../definitions/SetEnqueueLoadBalancerPowerOffResponse";
import { GetLoadBalancerNotifications } from "../definitions/GetLoadBalancerNotifications";
import { GetLoadBalancerNotificationsResponse } from "../definitions/GetLoadBalancerNotificationsResponse";
import { SetEnqueueLoadBalancerStart } from "../definitions/SetEnqueueLoadBalancerStart";
import { SetEnqueueLoadBalancerStartResponse } from "../definitions/SetEnqueueLoadBalancerStartResponse";
import { SetAddLoadBalancerContacts } from "../definitions/SetAddLoadBalancerContacts";
import { SetAddLoadBalancerContactsResponse } from "../definitions/SetAddLoadBalancerContactsResponse";
import { SetRemoveLoadBalancerContacts } from "../definitions/SetRemoveLoadBalancerContacts";
import { SetRemoveLoadBalancerContactsResponse } from "../definitions/SetRemoveLoadBalancerContactsResponse";
import { SetEnqueueLoadBalancerAddInstances } from "../definitions/SetEnqueueLoadBalancerAddInstances";
import { SetEnqueueLoadBalancerAddInstancesResponse } from "../definitions/SetEnqueueLoadBalancerAddInstancesResponse";
import { SetEnqueueLoadBalancerRemoveInstances } from "../definitions/SetEnqueueLoadBalancerRemoveInstances";
import { SetEnqueueLoadBalancerRemoveInstancesResponse } from "../definitions/SetEnqueueLoadBalancerRemoveInstancesResponse";
import { SetModifyLoadBalancer } from "../definitions/SetModifyLoadBalancer";
import { SetModifyLoadBalancerResponse } from "../definitions/SetModifyLoadBalancerResponse";
import { SetAddLoadBalancerRule } from "../definitions/SetAddLoadBalancerRule";
import { SetAddLoadBalancerRuleResponse } from "../definitions/SetAddLoadBalancerRuleResponse";
import { SetRemoveLoadBalancerRule } from "../definitions/SetRemoveLoadBalancerRule";
import { SetRemoveLoadBalancerRuleResponse } from "../definitions/SetRemoveLoadBalancerRuleResponse";
import { SetEnqueueReinitializeLoadBalancer } from "../definitions/SetEnqueueReinitializeLoadBalancer";
import { SetEnqueueReinitializeLoadBalancerResponse } from "../definitions/SetEnqueueReinitializeLoadBalancerResponse";
import { GetPreConfiguredPackages } from "../definitions/GetPreConfiguredPackages";
import { GetPreConfiguredPackagesResponse } from "../definitions/GetPreConfiguredPackagesResponse";
import { GetAdditionalIpServices1 } from "../definitions/GetAdditionalIpServices1";
import { GetAdditionalIpServicesResponse1 } from "../definitions/GetAdditionalIpServicesResponse1";
import { SetEnqueueReinitializeServer } from "../definitions/SetEnqueueReinitializeServer";
import { SetEnqueueReinitializeServerResponse } from "../definitions/SetEnqueueReinitializeServerResponse";
import { GetAllCloudIpAddresses } from "../definitions/GetAllCloudIpAddresses";
import { GetAllCloudIpAddressesResponse } from "../definitions/GetAllCloudIpAddressesResponse";
import { SetEnqueueSetReverseDns } from "../definitions/SetEnqueueSetReverseDns";
import { SetEnqueueSetReverseDnsResponse } from "../definitions/SetEnqueueSetReverseDnsResponse";
import { SetEnqueueResetReverseDns } from "../definitions/SetEnqueueResetReverseDns";
import { SetEnqueueResetReverseDnsResponse } from "../definitions/SetEnqueueResetReverseDnsResponse";
import { GetReverseDns } from "../definitions/GetReverseDns";
import { GetReverseDnsResponse } from "../definitions/GetReverseDnsResponse";
import { IsLuckySmartAvailable } from "../definitions/IsLuckySmartAvailable";
import { IsLuckySmartAvailableResponse } from "../definitions/IsLuckySmartAvailableResponse";
import { GetLastSoldOutSettingItemList } from "../definitions/GetLastSoldOutSettingItemList";
import { GetLastSoldOutSettingItemListResponse } from "../definitions/GetLastSoldOutSettingItemListResponse";
import { GetHybridLinks } from "../definitions/GetHybridLinks";
import { GetHybridLinksResponse } from "../definitions/GetHybridLinksResponse";
import { GetHybridLinksPricingTypes } from "../definitions/GetHybridLinksPricingTypes";
import { GetHybridLinksPricingTypesResponse } from "../definitions/GetHybridLinksPricingTypesResponse";
import { SetEnqueueCreateHybridLink } from "../definitions/SetEnqueueCreateHybridLink";
import { SetEnqueueCreateHybridLinkResponse } from "../definitions/SetEnqueueCreateHybridLinkResponse";
import { SetEnqueueDeleteHybridLink } from "../definitions/SetEnqueueDeleteHybridLink";
import { SetEnqueueDeleteHybridLinkResponse } from "../definitions/SetEnqueueDeleteHybridLinkResponse";
import { GetPurchasedPrivateCloudsBase } from "../definitions/GetPurchasedPrivateCloudsBase";
import { GetPurchasedPrivateCloudsBaseResponse } from "../definitions/GetPurchasedPrivateCloudsBaseResponse";
import { GetCountries } from "../definitions/GetCountries";
import { GetCountriesResponse } from "../definitions/GetCountriesResponse";
import { GetSharedStoragePricingTypes } from "../definitions/GetSharedStoragePricingTypes";
import { GetSharedStoragePricingTypesResponse } from "../definitions/GetSharedStoragePricingTypesResponse";
import { GetSharedStorageDetails } from "../definitions/GetSharedStorageDetails";
import { GetSharedStorageDetailsResponse } from "../definitions/GetSharedStorageDetailsResponse";
import { RenameHybridLink } from "../definitions/RenameHybridLink";
import { RenameHybridLinkResponse } from "../definitions/RenameHybridLinkResponse";
import { PlannedChangePrivateCloudWindowsLicenseDeletion } from "../definitions/PlannedChangePrivateCloudWindowsLicenseDeletion";
import { PlannedChangePrivateCloudWindowsLicenseDeletionResponse } from "../definitions/PlannedChangePrivateCloudWindowsLicenseDeletionResponse";
import { PlannedChangePrivateCloudLicenseDeletion } from "../definitions/PlannedChangePrivateCloudLicenseDeletion";
import { PlannedChangePrivateCloudLicenseDeletionResponse } from "../definitions/PlannedChangePrivateCloudLicenseDeletionResponse";
import { ChangePrivateCloudPassword } from "../definitions/ChangePrivateCloudPassword";
import { ChangePrivateCloudPasswordResponse } from "../definitions/ChangePrivateCloudPasswordResponse";
import { ChangeZertoPassword } from "../definitions/ChangeZertoPassword";
import { ChangeZertoPasswordResponse } from "../definitions/ChangeZertoPasswordResponse";
import { GetVirtualMachinePricingTypes } from "../definitions/GetVirtualMachinePricingTypes";
import { GetVirtualMachinePricingTypesResponse } from "../definitions/GetVirtualMachinePricingTypesResponse";
import { SetEnqueueModifyVirtualMachinePackage } from "../definitions/SetEnqueueModifyVirtualMachinePackage";
import { SetEnqueueModifyVirtualMachinePackageResponse } from "../definitions/SetEnqueueModifyVirtualMachinePackageResponse";
import { ServerPlannedChangeDeletion } from "../definitions/ServerPlannedChangeDeletion";
import { ServerPlannedChangeDeletionResponse } from "../definitions/ServerPlannedChangeDeletionResponse";
import { GetHypervisorTemplatesPriority } from "../definitions/GetHypervisorTemplatesPriority";
import { GetHypervisorTemplatesPriorityResponse } from "../definitions/GetHypervisorTemplatesPriorityResponse";
import { GetHypervisorTemplates } from "../definitions/GetHypervisorTemplates";
import { GetHypervisorTemplatesResponse } from "../definitions/GetHypervisorTemplatesResponse";
import { GetHypervisorTemplateDetails } from "../definitions/GetHypervisorTemplateDetails";
import { GetHypervisorTemplateDetailsResponse } from "../definitions/GetHypervisorTemplateDetailsResponse";
import { GetPrivateCloudPricingTypes } from "../definitions/GetPrivateCloudPricingTypes";
import { GetPrivateCloudPricingTypesResponse } from "../definitions/GetPrivateCloudPricingTypesResponse";
import { GetPrivateCloudResources } from "../definitions/GetPrivateCloudResources";
import { GetPrivateCloudResourcesResponse } from "../definitions/GetPrivateCloudResourcesResponse";
import { GetPrivateCloudCustomProducts } from "../definitions/GetPrivateCloudCustomProducts";
import { GetPrivateCloudCustomProductsResponse } from "../definitions/GetPrivateCloudCustomProductsResponse";
import { GetPublicVLanForUser } from "../definitions/GetPublicVLanForUser";
import { GetPublicVLanForUserResponse } from "../definitions/GetPublicVLanForUserResponse";
import { ManageIp1 } from "../definitions/ManageIp1";
import { ManageIpResponse1 } from "../definitions/ManageIpResponse1";
import { GetPrivateCloudNamingBlacklists } from "../definitions/GetPrivateCloudNamingBlacklists";
import { GetPrivateCloudNamingBlacklistsResponse } from "../definitions/GetPrivateCloudNamingBlacklistsResponse";
import { CancelDeleteVirtualMachine } from "../definitions/CancelDeleteVirtualMachine";
import { CancelDeleteVirtualMachineResponse } from "../definitions/CancelDeleteVirtualMachineResponse";
import { CreateVpcUser1 } from "../definitions/CreateVpcUser1";
import { CreateVpcUserResponse1 } from "../definitions/CreateVpcUserResponse1";
import { GetVpcUsers1 } from "../definitions/GetVpcUsers1";
import { GetVpcUsersResponse2 } from "../definitions/GetVpcUsersResponse2";
import { RequestVpcUserOtpToken1 } from "../definitions/RequestVpcUserOtpToken1";
import { RequestVpcUserOtpTokenResponse1 } from "../definitions/RequestVpcUserOtpTokenResponse1";
import { SetVpcOtpStatus1 } from "../definitions/SetVpcOtpStatus1";
import { SetVpcOtpStatusResponse1 } from "../definitions/SetVpcOtpStatusResponse1";
import { ResetVpcUserPassword1 } from "../definitions/ResetVpcUserPassword1";
import { ResetVpcUserPasswordResponse1 } from "../definitions/ResetVpcUserPasswordResponse1";
import { DeleteVpcUser1 } from "../definitions/DeleteVpcUser1";
import { DeleteVpcUserResponse1 } from "../definitions/DeleteVpcUserResponse1";
import { VerifyVpcUserOtp1 } from "../definitions/VerifyVpcUserOtp1";
import { VerifyVpcUserOtpResponse1 } from "../definitions/VerifyVpcUserOtpResponse1";
import { GetVpcRoles1 } from "../definitions/GetVpcRoles1";
import { GetVpcRolesResponse1 } from "../definitions/GetVpcRolesResponse1";
import { UpdateVpcUser1 } from "../definitions/UpdateVpcUser1";
import { UpdateVpcUserResponse1 } from "../definitions/UpdateVpcUserResponse1";
import { SyncVpcUserOtpToken1 } from "../definitions/SyncVpcUserOtpToken1";
import { SyncVpcUserOtpTokenResponse1 } from "../definitions/SyncVpcUserOtpTokenResponse1";
import { RemoveOldIpFromVps1 } from "../definitions/RemoveOldIpFromVps1";
import { RemoveOldIpFromVpsResponse1 } from "../definitions/RemoveOldIpFromVpsResponse1";
import { GetUserAuthenticationToken } from "../definitions/GetUserAuthenticationToken";
import { GetUserAuthenticationTokenResponse } from "../definitions/GetUserAuthenticationTokenResponse";
import { GetCompanyByUrl } from "../definitions/GetCompanyByUrl";
import { GetCompanyByUrlResponse } from "../definitions/GetCompanyByUrlResponse";
import { GetHypervisorTypes } from "../definitions/GetHypervisorTypes";
import { GetHypervisorTypesResponse } from "../definitions/GetHypervisorTypesResponse";
import { GetHypervisors } from "../definitions/GetHypervisors";
import { GetHypervisorsResponse } from "../definitions/GetHypervisorsResponse";
import { GetApplianceTypes } from "../definitions/GetApplianceTypes";
import { GetApplianceTypesResponse } from "../definitions/GetApplianceTypesResponse";
import { GetAllTags } from "../definitions/GetAllTags";
import { GetAllTagsResponse } from "../definitions/GetAllTagsResponse";
import { GetHypervisorDetails } from "../definitions/GetHypervisorDetails";
import { GetHypervisorDetailsResponse } from "../definitions/GetHypervisorDetailsResponse";
import { GetVirtualDatacenter } from "../definitions/GetVirtualDatacenter";
import { GetVirtualDatacenterResponse } from "../definitions/GetVirtualDatacenterResponse";
import { GetVirtualDatacenterCost } from "../definitions/GetVirtualDatacenterCost";
import { GetVirtualDatacenterCostResponse } from "../definitions/GetVirtualDatacenterCostResponse";
import { GetServers } from "../definitions/GetServers";
import { GetServersResponse } from "../definitions/GetServersResponse";
import { GetServersList } from "../definitions/GetServersList";
import { GetServersListResponse } from "../definitions/GetServersListResponse";
import { GetPagedServersList } from "../definitions/GetPagedServersList";
import { GetPagedServersListResponse } from "../definitions/GetPagedServersListResponse";
import { GetServerDetails } from "../definitions/GetServerDetails";
import { GetServerDetailsResponse } from "../definitions/GetServerDetailsResponse";
import { GetCredit } from "../definitions/GetCredit";
import { GetCreditResponse } from "../definitions/GetCreditResponse";
import { GetPriceList } from "../definitions/GetPriceList";
import { GetPriceListResponse } from "../definitions/GetPriceListResponse";
import { GetPurchasedVLans } from "../definitions/GetPurchasedVLans";
import { GetPurchasedVLansResponse } from "../definitions/GetPurchasedVLansResponse";
import { GetPurchasedIpAddresses } from "../definitions/GetPurchasedIpAddresses";
import { GetPurchasedIpAddressesResponse } from "../definitions/GetPurchasedIpAddressesResponse";
import { GetOpenStackFlavors } from "../definitions/GetOpenStackFlavors";
import { GetOpenStackFlavorsResponse } from "../definitions/GetOpenStackFlavorsResponse";
import { GetJobs } from "../definitions/GetJobs";
import { GetJobsResponse } from "../definitions/GetJobsResponse";
import { GetLogs } from "../definitions/GetLogs";
import { GetLogsResponse } from "../definitions/GetLogsResponse";
import { GetOperationsLog } from "../definitions/GetOperationsLog";
import { GetOperationsLogResponse } from "../definitions/GetOperationsLogResponse";
import { GetDatacenterConfigurations } from "../definitions/GetDatacenterConfigurations";
import { GetDatacenterConfigurationsResponse } from "../definitions/GetDatacenterConfigurationsResponse";
import { GetCustomVirtualDisks } from "../definitions/GetCustomVirtualDisks";
import { GetCustomVirtualDisksResponse } from "../definitions/GetCustomVirtualDisksResponse";
import { GetIsos } from "../definitions/GetIsos";
import { GetIsosResponse } from "../definitions/GetIsosResponse";
import { GetUserInfo } from "../definitions/GetUserInfo";
import { GetUserInfoResponse } from "../definitions/GetUserInfoResponse";
import { GetPurchasedFtp1 } from "../definitions/GetPurchasedFtp1";
import { GetPurchasedFtpResponse1 } from "../definitions/GetPurchasedFtpResponse1";
import { GetNews } from "../definitions/GetNews";
import { GetNewsResponse } from "../definitions/GetNewsResponse";
import { GetScheduledOperations } from "../definitions/GetScheduledOperations";
import { GetScheduledOperationsResponse } from "../definitions/GetScheduledOperationsResponse";
import { GetServerSchedulesLogs } from "../definitions/GetServerSchedulesLogs";
import { GetServerSchedulesLogsResponse } from "../definitions/GetServerSchedulesLogsResponse";
import { GetSchedulerDataTypes } from "../definitions/GetSchedulerDataTypes";
import { GetSchedulerDataTypesResponse } from "../definitions/GetSchedulerDataTypesResponse";
import { GetTemplateDetails } from "../definitions/GetTemplateDetails";
import { GetTemplateDetailsResponse } from "../definitions/GetTemplateDetailsResponse";
import { GetTemplateCategories } from "../definitions/GetTemplateCategories";
import { GetTemplateCategoriesResponse } from "../definitions/GetTemplateCategoriesResponse";
import { GetTemplateLicenses } from "../definitions/GetTemplateLicenses";
import { GetTemplateLicensesResponse } from "../definitions/GetTemplateLicensesResponse";
import { GetAvailablePersonalTemplates } from "../definitions/GetAvailablePersonalTemplates";
import { GetAvailablePersonalTemplatesResponse } from "../definitions/GetAvailablePersonalTemplatesResponse";
import { GetSystemStatusHistory } from "../definitions/GetSystemStatusHistory";
import { GetSystemStatusHistoryResponse } from "../definitions/GetSystemStatusHistoryResponse";
import { GetSharedStorages } from "../definitions/GetSharedStorages";
import { GetSharedStoragesResponse } from "../definitions/GetSharedStoragesResponse";
import { GetAdditionalServices } from "../definitions/GetAdditionalServices";
import { GetAdditionalServicesResponse } from "../definitions/GetAdditionalServicesResponse";
import { GetPurchasedAdditionalServices } from "../definitions/GetPurchasedAdditionalServices";
import { GetPurchasedAdditionalServicesResponse } from "../definitions/GetPurchasedAdditionalServicesResponse";
import { GetRemoteAccessUrl } from "../definitions/GetRemoteAccessUrl";
import { GetRemoteAccessUrlResponse } from "../definitions/GetRemoteAccessUrlResponse";
import { GetRemoteAccessUrlEx } from "../definitions/GetRemoteAccessUrlEx";
import { GetRemoteAccessUrlExResponse } from "../definitions/GetRemoteAccessUrlExResponse";
import { GetRemoteAccessUrlAsyncResponse } from "../definitions/GetRemoteAccessUrlAsyncResponse";
import { GetRemoteAccessUrlAsyncResponseResponse } from "../definitions/GetRemoteAccessUrlAsyncResponseResponse";
import { GetVmPerformance1 } from "../definitions/GetVmPerformance1";
import { GetVmPerformanceResponse1 } from "../definitions/GetVmPerformanceResponse1";
import { GetVmPerformances1 } from "../definitions/GetVmPerformances1";
import { GetVmPerformancesResponse1 } from "../definitions/GetVmPerformancesResponse1";
import { GetVmMetrics1 } from "../definitions/GetVmMetrics1";
import { GetVmMetricsResponse1 } from "../definitions/GetVmMetricsResponse1";
import { GetVirtualMachineCost } from "../definitions/GetVirtualMachineCost";
import { GetVirtualMachineCostResponse } from "../definitions/GetVirtualMachineCostResponse";
import { GetVirtualMachineResourcesProducts } from "../definitions/GetVirtualMachineResourcesProducts";
import { GetVirtualMachineResourcesProductsResponse } from "../definitions/GetVirtualMachineResourcesProductsResponse";
import { CheckEnqueueServerCreation } from "../definitions/CheckEnqueueServerCreation";
import { CheckEnqueueServerCreationResponse } from "../definitions/CheckEnqueueServerCreationResponse";
import { SetEnqueueServerCreation } from "../definitions/SetEnqueueServerCreation";
import { SetEnqueueServerCreationResponse } from "../definitions/SetEnqueueServerCreationResponse";
import { SetEnqueueServerCreationEx } from "../definitions/SetEnqueueServerCreationEx";
import { SetEnqueueServerCreationExResponse } from "../definitions/SetEnqueueServerCreationExResponse";
import { SetEnqueueServerUpdate } from "../definitions/SetEnqueueServerUpdate";
import { SetEnqueueServerUpdateResponse } from "../definitions/SetEnqueueServerUpdateResponse";
import { SetEnqueueServerStart } from "../definitions/SetEnqueueServerStart";
import { SetEnqueueServerStartResponse } from "../definitions/SetEnqueueServerStartResponse";
import { SetEnqueueServerStop } from "../definitions/SetEnqueueServerStop";
import { SetEnqueueServerStopResponse } from "../definitions/SetEnqueueServerStopResponse";
import { SetEnqueueServerDeletion } from "../definitions/SetEnqueueServerDeletion";
import { SetEnqueueServerDeletionResponse } from "../definitions/SetEnqueueServerDeletionResponse";
import { SetEnqueueServerReset } from "../definitions/SetEnqueueServerReset";
import { SetEnqueueServerResetResponse } from "../definitions/SetEnqueueServerResetResponse";
import { SetEnqueueServerRestart } from "../definitions/SetEnqueueServerRestart";
import { SetEnqueueServerRestartResponse } from "../definitions/SetEnqueueServerRestartResponse";
import { SetEnqueueServerPowerOff } from "../definitions/SetEnqueueServerPowerOff";
import { SetEnqueueServerPowerOffResponse } from "../definitions/SetEnqueueServerPowerOffResponse";
import { SetEnqueueServerArchiviation } from "../definitions/SetEnqueueServerArchiviation";
import { SetEnqueueServerArchiviationResponse } from "../definitions/SetEnqueueServerArchiviationResponse";
import { SetEnqueueServerRestore } from "../definitions/SetEnqueueServerRestore";
import { SetEnqueueServerRestoreResponse } from "../definitions/SetEnqueueServerRestoreResponse";
import { SetRenameServer } from "../definitions/SetRenameServer";
import { SetRenameServerResponse } from "../definitions/SetRenameServerResponse";
import { SetEnqueueMountDvdIso } from "../definitions/SetEnqueueMountDvdIso";
import { SetEnqueueMountDvdIsoResponse } from "../definitions/SetEnqueueMountDvdIsoResponse";
import { SetEnqueueUnmountDvdIso } from "../definitions/SetEnqueueUnmountDvdIso";
import { SetEnqueueUnmountDvdIsoResponse } from "../definitions/SetEnqueueUnmountDvdIsoResponse";
import { SetEnqueueVirtualDiskExport } from "../definitions/SetEnqueueVirtualDiskExport";
import { SetEnqueueVirtualDiskExportResponse } from "../definitions/SetEnqueueVirtualDiskExportResponse";
import { SetEnqueueVirtualDiskManage } from "../definitions/SetEnqueueVirtualDiskManage";
import { SetEnqueueVirtualDiskManageResponse } from "../definitions/SetEnqueueVirtualDiskManageResponse";
import { SetEnqueueServerSnapshot } from "../definitions/SetEnqueueServerSnapshot";
import { SetEnqueueServerSnapshotResponse } from "../definitions/SetEnqueueServerSnapshotResponse";
import { SetEnqueuePersonalTemplateCreation } from "../definitions/SetEnqueuePersonalTemplateCreation";
import { SetEnqueuePersonalTemplateCreationResponse } from "../definitions/SetEnqueuePersonalTemplateCreationResponse";
import { SetChangeNoteServer } from "../definitions/SetChangeNoteServer";
import { SetChangeNoteServerResponse } from "../definitions/SetChangeNoteServerResponse";
import { SetPurchaseIpAddress } from "../definitions/SetPurchaseIpAddress";
import { SetPurchaseIpAddressResponse } from "../definitions/SetPurchaseIpAddressResponse";
import { SetRemoveIpAddress } from "../definitions/SetRemoveIpAddress";
import { SetRemoveIpAddressResponse } from "../definitions/SetRemoveIpAddressResponse";
import { SetEnqueueAssociateIpAddress } from "../definitions/SetEnqueueAssociateIpAddress";
import { SetEnqueueAssociateIpAddressResponse } from "../definitions/SetEnqueueAssociateIpAddressResponse";
import { SetEnqueueDeassociateIpAddress } from "../definitions/SetEnqueueDeassociateIpAddress";
import { SetEnqueueDeassociateIpAddressResponse } from "../definitions/SetEnqueueDeassociateIpAddressResponse";
import { SetPurchaseVLan } from "../definitions/SetPurchaseVLan";
import { SetPurchaseVLanResponse } from "../definitions/SetPurchaseVLanResponse";
import { SetRemoveVLan } from "../definitions/SetRemoveVLan";
import { SetRemoveVLanResponse } from "../definitions/SetRemoveVLanResponse";
import { SetRenameVLan } from "../definitions/SetRenameVLan";
import { SetRenameVLanResponse } from "../definitions/SetRenameVLanResponse";
import { SetEnqueueAssociateVLan } from "../definitions/SetEnqueueAssociateVLan";
import { SetEnqueueAssociateVLanResponse } from "../definitions/SetEnqueueAssociateVLanResponse";
import { SetEnqueueDeassociateVLan } from "../definitions/SetEnqueueDeassociateVLan";
import { SetEnqueueDeassociateVLanResponse } from "../definitions/SetEnqueueDeassociateVLanResponse";
import { SetEnqueueCreateFtpAccount1 } from "../definitions/SetEnqueueCreateFtpAccount1";
import { SetEnqueueCreateFtpAccountResponse1 } from "../definitions/SetEnqueueCreateFtpAccountResponse1";
import { SetEnqueueResizeFtpAccount1 } from "../definitions/SetEnqueueResizeFtpAccount1";
import { SetEnqueueResizeFtpAccountResponse1 } from "../definitions/SetEnqueueResizeFtpAccountResponse1";
import { SetReadNews } from "../definitions/SetReadNews";
import { SetReadNewsResponse } from "../definitions/SetReadNewsResponse";
import { SetAddServerScheduledOperation } from "../definitions/SetAddServerScheduledOperation";
import { SetAddServerScheduledOperationResponse } from "../definitions/SetAddServerScheduledOperationResponse";
import { SetUpdateServerScheduledOperation } from "../definitions/SetUpdateServerScheduledOperation";
import { SetUpdateServerScheduledOperationResponse } from "../definitions/SetUpdateServerScheduledOperationResponse";
import { SetRemoveServerScheduledOperation } from "../definitions/SetRemoveServerScheduledOperation";
import { SetRemoveServerScheduledOperationResponse } from "../definitions/SetRemoveServerScheduledOperationResponse";
import { SetEnqueuePurchaseSharedStorage } from "../definitions/SetEnqueuePurchaseSharedStorage";
import { SetEnqueuePurchaseSharedStorageResponse } from "../definitions/SetEnqueuePurchaseSharedStorageResponse";
import { SetEnqueueRemoveSharedStorage } from "../definitions/SetEnqueueRemoveSharedStorage";
import { SetEnqueueRemoveSharedStorageResponse } from "../definitions/SetEnqueueRemoveSharedStorageResponse";
import { SetEnqueueModifySharedStorage } from "../definitions/SetEnqueueModifySharedStorage";
import { SetEnqueueModifySharedStorageResponse } from "../definitions/SetEnqueueModifySharedStorageResponse";
import { SetEnqueueAddIqnSharedStorage1 } from "../definitions/SetEnqueueAddIqnSharedStorage1";
import { SetEnqueueAddIqnSharedStorageResponse1 } from "../definitions/SetEnqueueAddIqnSharedStorageResponse1";
import { SetEnqueueRemoveIqnSharedStorage1 } from "../definitions/SetEnqueueRemoveIqnSharedStorage1";
import { SetEnqueueRemoveIqnSharedStorageResponse1 } from "../definitions/SetEnqueueRemoveIqnSharedStorageResponse1";
import { SetRenameSharedStorage } from "../definitions/SetRenameSharedStorage";
import { SetRenameSharedStorageResponse } from "../definitions/SetRenameSharedStorageResponse";
import { SetUpdatePersonalTemplate } from "../definitions/SetUpdatePersonalTemplate";
import { SetUpdatePersonalTemplateResponse } from "../definitions/SetUpdatePersonalTemplateResponse";
import { SetRemovePersonalTemplate } from "../definitions/SetRemovePersonalTemplate";
import { SetRemovePersonalTemplateResponse } from "../definitions/SetRemovePersonalTemplateResponse";
import { SetPurchasedAdditionalServices } from "../definitions/SetPurchasedAdditionalServices";
import { SetPurchasedAdditionalServicesResponse } from "../definitions/SetPurchasedAdditionalServicesResponse";
import { SetControlToolActive } from "../definitions/SetControlToolActive";
import { SetControlToolActiveResponse } from "../definitions/SetControlToolActiveResponse";
import { SetControlToolDisable } from "../definitions/SetControlToolDisable";
import { SetControlToolDisableResponse } from "../definitions/SetControlToolDisableResponse";
import { GetControlToolCheck } from "../definitions/GetControlToolCheck";
import { GetControlToolCheckResponse } from "../definitions/GetControlToolCheckResponse";
import { GetControlToolActivationRequests } from "../definitions/GetControlToolActivationRequests";
import { GetControlToolActivationRequestsResponse } from "../definitions/GetControlToolActivationRequestsResponse";
import { SetControlToolActivationRequest } from "../definitions/SetControlToolActivationRequest";
import { SetControlToolActivationRequestResponse } from "../definitions/SetControlToolActivationRequestResponse";
import { GetNetworkAdapterConfiguration } from "../definitions/GetNetworkAdapterConfiguration";
import { GetNetworkAdapterConfigurationResponse } from "../definitions/GetNetworkAdapterConfigurationResponse";
import { GetControlToolCommandResult } from "../definitions/GetControlToolCommandResult";
import { GetControlToolCommandResultResponse } from "../definitions/GetControlToolCommandResultResponse";
import { SetEnqueueUpdateControlTool } from "../definitions/SetEnqueueUpdateControlTool";
import { SetEnqueueUpdateControlToolResponse } from "../definitions/SetEnqueueUpdateControlToolResponse";
import { GetScheduleOccurrences } from "../definitions/GetScheduleOccurrences";
import { GetScheduleOccurrencesResponse } from "../definitions/GetScheduleOccurrencesResponse";
import { GetVdcGraph1 } from "../definitions/GetVdcGraph1";
import { GetVdcGraphResponse1 } from "../definitions/GetVdcGraphResponse1";
import { SetAddVdcGraph1 } from "../definitions/SetAddVdcGraph1";
import { SetAddVdcGraphResponse1 } from "../definitions/SetAddVdcGraphResponse1";
import { SetUpdateVdcGraph1 } from "../definitions/SetUpdateVdcGraph1";
import { SetUpdateVdcGraphResponse1 } from "../definitions/SetUpdateVdcGraphResponse1";
import { GetAssistanceLanguages } from "../definitions/GetAssistanceLanguages";
import { GetAssistanceLanguagesResponse } from "../definitions/GetAssistanceLanguagesResponse";
import { GetAssistanceLanguagesList } from "../definitions/GetAssistanceLanguagesList";
import { GetAssistanceLanguagesListResponse } from "../definitions/GetAssistanceLanguagesListResponse";
import { SetUpdateAssistanceRequest } from "../definitions/SetUpdateAssistanceRequest";
import { SetUpdateAssistanceRequestResponse } from "../definitions/SetUpdateAssistanceRequestResponse";
import { GetAssistanceRequestDetails } from "../definitions/GetAssistanceRequestDetails";
import { GetAssistanceRequestDetailsResponse } from "../definitions/GetAssistanceRequestDetailsResponse";
import { SetAssistanceQuotationAcceptance } from "../definitions/SetAssistanceQuotationAcceptance";
import { SetAssistanceQuotationAcceptanceResponse } from "../definitions/SetAssistanceQuotationAcceptanceResponse";
import { SetSendAssistanceRequest } from "../definitions/SetSendAssistanceRequest";
import { SetSendAssistanceRequestResponse } from "../definitions/SetSendAssistanceRequestResponse";
import { SetInsertAssistanceRequest } from "../definitions/SetInsertAssistanceRequest";
import { SetInsertAssistanceRequestResponse } from "../definitions/SetInsertAssistanceRequestResponse";
import { GetUserAssistanceRequests } from "../definitions/GetUserAssistanceRequests";
import { GetUserAssistanceRequestsResponse } from "../definitions/GetUserAssistanceRequestsResponse";
import { SetEnqueuePurchasePrivateCloud } from "../definitions/SetEnqueuePurchasePrivateCloud";
import { SetEnqueuePurchasePrivateCloudResponse } from "../definitions/SetEnqueuePurchasePrivateCloudResponse";
import { GetPrivateCloudResourcesTypes } from "../definitions/GetPrivateCloudResourcesTypes";
import { GetPrivateCloudResourcesTypesResponse } from "../definitions/GetPrivateCloudResourcesTypesResponse";
import { GetPrivateCloudResourcesTypes2 } from "../definitions/GetPrivateCloudResourcesTypes2";
import { GetPrivateCloudResourcesTypes2Response } from "../definitions/GetPrivateCloudResourcesTypes2Response";
import { GetPurchasedPrivateClouds } from "../definitions/GetPurchasedPrivateClouds";
import { GetPurchasedPrivateCloudsResponse } from "../definitions/GetPurchasedPrivateCloudsResponse";
import { GetPurchasedPrivateCloudDetails } from "../definitions/GetPurchasedPrivateCloudDetails";
import { GetPurchasedPrivateCloudDetailsResponse } from "../definitions/GetPurchasedPrivateCloudDetailsResponse";
import { GetPurchasedPrivateCloudDetails2 } from "../definitions/GetPurchasedPrivateCloudDetails2";
import { GetPurchasedPrivateCloudDetails2Response } from "../definitions/GetPurchasedPrivateCloudDetails2Response";
import { SetEnqueueModifyPrivateCloudResources } from "../definitions/SetEnqueueModifyPrivateCloudResources";
import { SetEnqueueModifyPrivateCloudResourcesResponse } from "../definitions/SetEnqueueModifyPrivateCloudResourcesResponse";
import { SetEnqueuePrivateCloudDeletion } from "../definitions/SetEnqueuePrivateCloudDeletion";
import { SetEnqueuePrivateCloudDeletionResponse } from "../definitions/SetEnqueuePrivateCloudDeletionResponse";
import { CancelDeletePrivateCloudInstance } from "../definitions/CancelDeletePrivateCloudInstance";
import { CancelDeletePrivateCloudInstanceResponse } from "../definitions/CancelDeletePrivateCloudInstanceResponse";
import { SetEnqueuePrivateCloudActivation } from "../definitions/SetEnqueuePrivateCloudActivation";
import { SetEnqueuePrivateCloudActivationResponse } from "../definitions/SetEnqueuePrivateCloudActivationResponse";
import { GetPrivateCloudOrganizations } from "../definitions/GetPrivateCloudOrganizations";
import { GetPrivateCloudOrganizationsResponse } from "../definitions/GetPrivateCloudOrganizationsResponse";
import { GetPrivateCloudOrganizationDetails } from "../definitions/GetPrivateCloudOrganizationDetails";
import { GetPrivateCloudOrganizationDetailsResponse } from "../definitions/GetPrivateCloudOrganizationDetailsResponse";
import { GetHybridLinksbyOrg } from "../definitions/GetHybridLinksbyOrg";
import { GetHybridLinksbyOrgResponse } from "../definitions/GetHybridLinksbyOrgResponse";
import { GetActivatedPrivateCloudFeatures } from "../definitions/GetActivatedPrivateCloudFeatures";
import { GetActivatedPrivateCloudFeaturesResponse } from "../definitions/GetActivatedPrivateCloudFeaturesResponse";
import { SetEnqueueModifyPrivateCloudOrganization } from "../definitions/SetEnqueueModifyPrivateCloudOrganization";
import { SetEnqueueModifyPrivateCloudOrganizationResponse } from "../definitions/SetEnqueueModifyPrivateCloudOrganizationResponse";
import { SetEnqueueLoadBalancerCreation } from "../definitions/SetEnqueueLoadBalancerCreation";
import { SetEnqueueLoadBalancerCreationResponse } from "../definitions/SetEnqueueLoadBalancerCreationResponse";
import { SetEnqueueLoadBalancerDeletion } from "../definitions/SetEnqueueLoadBalancerDeletion";
import { SetEnqueueLoadBalancerDeletionResponse } from "../definitions/SetEnqueueLoadBalancerDeletionResponse";
import { GetLoadBalancers } from "../definitions/GetLoadBalancers";
import { GetLoadBalancersResponse } from "../definitions/GetLoadBalancersResponse";

export interface BasicHttpsEndpoint {
    GetLoadBalancerLoads(getLoadBalancerLoads: GetLoadBalancerLoads, callback: (err: any, result: GetLoadBalancerLoadsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetLoadBalancerRuleStatistics(getLoadBalancerRuleStatistics: GetLoadBalancerRuleStatistics, callback: (err: any, result: GetLoadBalancerRuleStatisticsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueLoadBalancerPowerOff(setEnqueueLoadBalancerPowerOff: SetEnqueueLoadBalancerPowerOff, callback: (err: any, result: SetEnqueueLoadBalancerPowerOffResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetLoadBalancerNotifications(getLoadBalancerNotifications: GetLoadBalancerNotifications, callback: (err: any, result: GetLoadBalancerNotificationsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueLoadBalancerStart(setEnqueueLoadBalancerStart: SetEnqueueLoadBalancerStart, callback: (err: any, result: SetEnqueueLoadBalancerStartResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetAddLoadBalancerContacts(setAddLoadBalancerContacts: SetAddLoadBalancerContacts, callback: (err: any, result: SetAddLoadBalancerContactsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRemoveLoadBalancerContacts(setRemoveLoadBalancerContacts: SetRemoveLoadBalancerContacts, callback: (err: any, result: SetRemoveLoadBalancerContactsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueLoadBalancerAddInstances(setEnqueueLoadBalancerAddInstances: SetEnqueueLoadBalancerAddInstances, callback: (err: any, result: SetEnqueueLoadBalancerAddInstancesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueLoadBalancerRemoveInstances(setEnqueueLoadBalancerRemoveInstances: SetEnqueueLoadBalancerRemoveInstances, callback: (err: any, result: SetEnqueueLoadBalancerRemoveInstancesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetModifyLoadBalancer(setModifyLoadBalancer: SetModifyLoadBalancer, callback: (err: any, result: SetModifyLoadBalancerResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetAddLoadBalancerRule(setAddLoadBalancerRule: SetAddLoadBalancerRule, callback: (err: any, result: SetAddLoadBalancerRuleResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRemoveLoadBalancerRule(setRemoveLoadBalancerRule: SetRemoveLoadBalancerRule, callback: (err: any, result: SetRemoveLoadBalancerRuleResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueReinitializeLoadBalancer(setEnqueueReinitializeLoadBalancer: SetEnqueueReinitializeLoadBalancer, callback: (err: any, result: SetEnqueueReinitializeLoadBalancerResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPreConfiguredPackages(getPreConfiguredPackages: GetPreConfiguredPackages, callback: (err: any, result: GetPreConfiguredPackagesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAdditionalIPServices(getAdditionalIpServices: GetAdditionalIpServices1, callback: (err: any, result: GetAdditionalIpServicesResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueReinitializeServer(setEnqueueReinitializeServer: SetEnqueueReinitializeServer, callback: (err: any, result: SetEnqueueReinitializeServerResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAllCloudIpAddresses(getAllCloudIpAddresses: GetAllCloudIpAddresses, callback: (err: any, result: GetAllCloudIpAddressesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueSetReverseDns(setEnqueueSetReverseDns: SetEnqueueSetReverseDns, callback: (err: any, result: SetEnqueueSetReverseDnsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueResetReverseDns(setEnqueueResetReverseDns: SetEnqueueResetReverseDns, callback: (err: any, result: SetEnqueueResetReverseDnsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetReverseDns(getReverseDns: GetReverseDns, callback: (err: any, result: GetReverseDnsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    IsLuckySmartAvailable(isLuckySmartAvailable: IsLuckySmartAvailable, callback: (err: any, result: IsLuckySmartAvailableResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetLastSoldOutSettingItemList(getLastSoldOutSettingItemList: GetLastSoldOutSettingItemList, callback: (err: any, result: GetLastSoldOutSettingItemListResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHybridLinks(getHybridLinks: GetHybridLinks, callback: (err: any, result: GetHybridLinksResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHybridLinksPricingTypes(getHybridLinksPricingTypes: GetHybridLinksPricingTypes, callback: (err: any, result: GetHybridLinksPricingTypesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueCreateHybridLink(setEnqueueCreateHybridLink: SetEnqueueCreateHybridLink, callback: (err: any, result: SetEnqueueCreateHybridLinkResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueDeleteHybridLink(setEnqueueDeleteHybridLink: SetEnqueueDeleteHybridLink, callback: (err: any, result: SetEnqueueDeleteHybridLinkResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedPrivateCloudsBase(getPurchasedPrivateCloudsBase: GetPurchasedPrivateCloudsBase, callback: (err: any, result: GetPurchasedPrivateCloudsBaseResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetCountries(getCountries: GetCountries, callback: (err: any, result: GetCountriesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSharedStoragePricingTypes(getSharedStoragePricingTypes: GetSharedStoragePricingTypes, callback: (err: any, result: GetSharedStoragePricingTypesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSharedStorageDetails(getSharedStorageDetails: GetSharedStorageDetails, callback: (err: any, result: GetSharedStorageDetailsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    RenameHybridLink(renameHybridLink: RenameHybridLink, callback: (err: any, result: RenameHybridLinkResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    PlannedChangePrivateCloudWindowsLicenseDeletion(plannedChangePrivateCloudWindowsLicenseDeletion: PlannedChangePrivateCloudWindowsLicenseDeletion, callback: (err: any, result: PlannedChangePrivateCloudWindowsLicenseDeletionResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    PlannedChangePrivateCloudLicenseDeletion(plannedChangePrivateCloudLicenseDeletion: PlannedChangePrivateCloudLicenseDeletion, callback: (err: any, result: PlannedChangePrivateCloudLicenseDeletionResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ChangePrivateCloudPassword(changePrivateCloudPassword: ChangePrivateCloudPassword, callback: (err: any, result: ChangePrivateCloudPasswordResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ChangeZertoPassword(changeZertoPassword: ChangeZertoPassword, callback: (err: any, result: ChangeZertoPasswordResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVirtualMachinePricingTypes(getVirtualMachinePricingTypes: GetVirtualMachinePricingTypes, callback: (err: any, result: GetVirtualMachinePricingTypesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueModifyVirtualMachinePackage(setEnqueueModifyVirtualMachinePackage: SetEnqueueModifyVirtualMachinePackage, callback: (err: any, result: SetEnqueueModifyVirtualMachinePackageResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ServerPlannedChangeDeletion(serverPlannedChangeDeletion: ServerPlannedChangeDeletion, callback: (err: any, result: ServerPlannedChangeDeletionResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHypervisorTemplatesPriority(getHypervisorTemplatesPriority: GetHypervisorTemplatesPriority, callback: (err: any, result: GetHypervisorTemplatesPriorityResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHypervisorTemplates(getHypervisorTemplates: GetHypervisorTemplates, callback: (err: any, result: GetHypervisorTemplatesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHypervisorTemplateDetails(getHypervisorTemplateDetails: GetHypervisorTemplateDetails, callback: (err: any, result: GetHypervisorTemplateDetailsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudPricingTypes(getPrivateCloudPricingTypes: GetPrivateCloudPricingTypes, callback: (err: any, result: GetPrivateCloudPricingTypesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudResources(getPrivateCloudResources: GetPrivateCloudResources, callback: (err: any, result: GetPrivateCloudResourcesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudCustomProducts(getPrivateCloudCustomProducts: GetPrivateCloudCustomProducts, callback: (err: any, result: GetPrivateCloudCustomProductsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPublicVLanForUser(getPublicVLanForUser: GetPublicVLanForUser, callback: (err: any, result: GetPublicVLanForUserResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ManageIP(manageIp: ManageIp1, callback: (err: any, result: ManageIpResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudNamingBlacklists(getPrivateCloudNamingBlacklists: GetPrivateCloudNamingBlacklists, callback: (err: any, result: GetPrivateCloudNamingBlacklistsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CancelDeleteVirtualMachine(cancelDeleteVirtualMachine: CancelDeleteVirtualMachine, callback: (err: any, result: CancelDeleteVirtualMachineResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateVPCUser(createVpcUser: CreateVpcUser1, callback: (err: any, result: CreateVpcUserResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVPCUsers(getVpcUsers: GetVpcUsers1, callback: (err: any, result: GetVpcUsersResponse2, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    RequestVPCUserOtpToken(requestVpcUserOtpToken: RequestVpcUserOtpToken1, callback: (err: any, result: RequestVpcUserOtpTokenResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetVPCOtpStatus(setVpcOtpStatus: SetVpcOtpStatus1, callback: (err: any, result: SetVpcOtpStatusResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ResetVPCUserPassword(resetVpcUserPassword: ResetVpcUserPassword1, callback: (err: any, result: ResetVpcUserPasswordResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    DeleteVPCUser(deleteVpcUser: DeleteVpcUser1, callback: (err: any, result: DeleteVpcUserResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    VerifyVPCUserOtp(verifyVpcUserOtp: VerifyVpcUserOtp1, callback: (err: any, result: VerifyVpcUserOtpResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVPCRoles(getVpcRoles: GetVpcRoles1, callback: (err: any, result: GetVpcRolesResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    UpdateVPCUser(updateVpcUser: UpdateVpcUser1, callback: (err: any, result: UpdateVpcUserResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SyncVPCUserOtpToken(syncVpcUserOtpToken: SyncVpcUserOtpToken1, callback: (err: any, result: SyncVpcUserOtpTokenResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    RemoveOldIpFromVPS(removeOldIpFromVps: RemoveOldIpFromVps1, callback: (err: any, result: RemoveOldIpFromVpsResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetUserAuthenticationToken(getUserAuthenticationToken: GetUserAuthenticationToken, callback: (err: any, result: GetUserAuthenticationTokenResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetCompanyByUrl(getCompanyByUrl: GetCompanyByUrl, callback: (err: any, result: GetCompanyByUrlResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHypervisorTypes(getHypervisorTypes: GetHypervisorTypes, callback: (err: any, result: GetHypervisorTypesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHypervisors(getHypervisors: GetHypervisors, callback: (err: any, result: GetHypervisorsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetApplianceTypes(getApplianceTypes: GetApplianceTypes, callback: (err: any, result: GetApplianceTypesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAllTags(getAllTags: GetAllTags, callback: (err: any, result: GetAllTagsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHypervisorDetails(getHypervisorDetails: GetHypervisorDetails, callback: (err: any, result: GetHypervisorDetailsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVirtualDatacenter(getVirtualDatacenter: GetVirtualDatacenter, callback: (err: any, result: GetVirtualDatacenterResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVirtualDatacenterCost(getVirtualDatacenterCost: GetVirtualDatacenterCost, callback: (err: any, result: GetVirtualDatacenterCostResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetServers(getServers: GetServers, callback: (err: any, result: GetServersResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetServersList(getServersList: GetServersList, callback: (err: any, result: GetServersListResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPagedServersList(getPagedServersList: GetPagedServersList, callback: (err: any, result: GetPagedServersListResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetServerDetails(getServerDetails: GetServerDetails, callback: (err: any, result: GetServerDetailsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetCredit(getCredit: GetCredit, callback: (err: any, result: GetCreditResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPriceList(getPriceList: GetPriceList, callback: (err: any, result: GetPriceListResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedVLans(getPurchasedVLans: GetPurchasedVLans, callback: (err: any, result: GetPurchasedVLansResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedIpAddresses(getPurchasedIpAddresses: GetPurchasedIpAddresses, callback: (err: any, result: GetPurchasedIpAddressesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOpenStackFlavors(getOpenStackFlavors: GetOpenStackFlavors, callback: (err: any, result: GetOpenStackFlavorsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetJobs(getJobs: GetJobs, callback: (err: any, result: GetJobsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetLogs(getLogs: GetLogs, callback: (err: any, result: GetLogsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOperationsLog(getOperationsLog: GetOperationsLog, callback: (err: any, result: GetOperationsLogResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetDatacenterConfigurations(getDatacenterConfigurations: GetDatacenterConfigurations, callback: (err: any, result: GetDatacenterConfigurationsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetCustomVirtualDisks(getCustomVirtualDisks: GetCustomVirtualDisks, callback: (err: any, result: GetCustomVirtualDisksResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetIsos(getIsos: GetIsos, callback: (err: any, result: GetIsosResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetUserInfo(getUserInfo: GetUserInfo, callback: (err: any, result: GetUserInfoResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedFTP(getPurchasedFtp: GetPurchasedFtp1, callback: (err: any, result: GetPurchasedFtpResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetNews(getNews: GetNews, callback: (err: any, result: GetNewsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetScheduledOperations(getScheduledOperations: GetScheduledOperations, callback: (err: any, result: GetScheduledOperationsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetServerSchedulesLogs(getServerSchedulesLogs: GetServerSchedulesLogs, callback: (err: any, result: GetServerSchedulesLogsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSchedulerDataTypes(getSchedulerDataTypes: GetSchedulerDataTypes, callback: (err: any, result: GetSchedulerDataTypesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetTemplateDetails(getTemplateDetails: GetTemplateDetails, callback: (err: any, result: GetTemplateDetailsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetTemplateCategories(getTemplateCategories: GetTemplateCategories, callback: (err: any, result: GetTemplateCategoriesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetTemplateLicenses(getTemplateLicenses: GetTemplateLicenses, callback: (err: any, result: GetTemplateLicensesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAvailablePersonalTemplates(getAvailablePersonalTemplates: GetAvailablePersonalTemplates, callback: (err: any, result: GetAvailablePersonalTemplatesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSystemStatusHistory(getSystemStatusHistory: GetSystemStatusHistory, callback: (err: any, result: GetSystemStatusHistoryResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSharedStorages(getSharedStorages: GetSharedStorages, callback: (err: any, result: GetSharedStoragesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAdditionalServices(getAdditionalServices: GetAdditionalServices, callback: (err: any, result: GetAdditionalServicesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedAdditionalServices(getPurchasedAdditionalServices: GetPurchasedAdditionalServices, callback: (err: any, result: GetPurchasedAdditionalServicesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetRemoteAccessUrl(getRemoteAccessUrl: GetRemoteAccessUrl, callback: (err: any, result: GetRemoteAccessUrlResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetRemoteAccessUrlEx(getRemoteAccessUrlEx: GetRemoteAccessUrlEx, callback: (err: any, result: GetRemoteAccessUrlExResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetRemoteAccessUrlAsyncResponse(getRemoteAccessUrlAsyncResponse: GetRemoteAccessUrlAsyncResponse, callback: (err: any, result: GetRemoteAccessUrlAsyncResponseResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVMPerformance(getVmPerformance: GetVmPerformance1, callback: (err: any, result: GetVmPerformanceResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVMPerformances(getVmPerformances: GetVmPerformances1, callback: (err: any, result: GetVmPerformancesResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVMMetrics(getVmMetrics: GetVmMetrics1, callback: (err: any, result: GetVmMetricsResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVirtualMachineCost(getVirtualMachineCost: GetVirtualMachineCost, callback: (err: any, result: GetVirtualMachineCostResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVirtualMachineResourcesProducts(getVirtualMachineResourcesProducts: GetVirtualMachineResourcesProducts, callback: (err: any, result: GetVirtualMachineResourcesProductsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CheckEnqueueServerCreation(checkEnqueueServerCreation: CheckEnqueueServerCreation, callback: (err: any, result: CheckEnqueueServerCreationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerCreation(setEnqueueServerCreation: SetEnqueueServerCreation, callback: (err: any, result: SetEnqueueServerCreationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerCreationEx(setEnqueueServerCreationEx: SetEnqueueServerCreationEx, callback: (err: any, result: SetEnqueueServerCreationExResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerUpdate(setEnqueueServerUpdate: SetEnqueueServerUpdate, callback: (err: any, result: SetEnqueueServerUpdateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerStart(setEnqueueServerStart: SetEnqueueServerStart, callback: (err: any, result: SetEnqueueServerStartResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerStop(setEnqueueServerStop: SetEnqueueServerStop, callback: (err: any, result: SetEnqueueServerStopResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerDeletion(setEnqueueServerDeletion: SetEnqueueServerDeletion, callback: (err: any, result: SetEnqueueServerDeletionResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerReset(setEnqueueServerReset: SetEnqueueServerReset, callback: (err: any, result: SetEnqueueServerResetResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerRestart(setEnqueueServerRestart: SetEnqueueServerRestart, callback: (err: any, result: SetEnqueueServerRestartResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerPowerOff(setEnqueueServerPowerOff: SetEnqueueServerPowerOff, callback: (err: any, result: SetEnqueueServerPowerOffResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerArchiviation(setEnqueueServerArchiviation: SetEnqueueServerArchiviation, callback: (err: any, result: SetEnqueueServerArchiviationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerRestore(setEnqueueServerRestore: SetEnqueueServerRestore, callback: (err: any, result: SetEnqueueServerRestoreResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRenameServer(setRenameServer: SetRenameServer, callback: (err: any, result: SetRenameServerResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueMountDvdIso(setEnqueueMountDvdIso: SetEnqueueMountDvdIso, callback: (err: any, result: SetEnqueueMountDvdIsoResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueUnmountDvdIso(setEnqueueUnmountDvdIso: SetEnqueueUnmountDvdIso, callback: (err: any, result: SetEnqueueUnmountDvdIsoResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueVirtualDiskExport(setEnqueueVirtualDiskExport: SetEnqueueVirtualDiskExport, callback: (err: any, result: SetEnqueueVirtualDiskExportResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueVirtualDiskManage(setEnqueueVirtualDiskManage: SetEnqueueVirtualDiskManage, callback: (err: any, result: SetEnqueueVirtualDiskManageResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueServerSnapshot(setEnqueueServerSnapshot: SetEnqueueServerSnapshot, callback: (err: any, result: SetEnqueueServerSnapshotResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueuePersonalTemplateCreation(setEnqueuePersonalTemplateCreation: SetEnqueuePersonalTemplateCreation, callback: (err: any, result: SetEnqueuePersonalTemplateCreationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetChangeNoteServer(setChangeNoteServer: SetChangeNoteServer, callback: (err: any, result: SetChangeNoteServerResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetPurchaseIpAddress(setPurchaseIpAddress: SetPurchaseIpAddress, callback: (err: any, result: SetPurchaseIpAddressResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRemoveIpAddress(setRemoveIpAddress: SetRemoveIpAddress, callback: (err: any, result: SetRemoveIpAddressResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueAssociateIpAddress(setEnqueueAssociateIpAddress: SetEnqueueAssociateIpAddress, callback: (err: any, result: SetEnqueueAssociateIpAddressResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueDeassociateIpAddress(setEnqueueDeassociateIpAddress: SetEnqueueDeassociateIpAddress, callback: (err: any, result: SetEnqueueDeassociateIpAddressResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetPurchaseVLan(setPurchaseVLan: SetPurchaseVLan, callback: (err: any, result: SetPurchaseVLanResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRemoveVLan(setRemoveVLan: SetRemoveVLan, callback: (err: any, result: SetRemoveVLanResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRenameVLan(setRenameVLan: SetRenameVLan, callback: (err: any, result: SetRenameVLanResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueAssociateVLan(setEnqueueAssociateVLan: SetEnqueueAssociateVLan, callback: (err: any, result: SetEnqueueAssociateVLanResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueDeassociateVLan(setEnqueueDeassociateVLan: SetEnqueueDeassociateVLan, callback: (err: any, result: SetEnqueueDeassociateVLanResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueCreateFTPAccount(setEnqueueCreateFtpAccount: SetEnqueueCreateFtpAccount1, callback: (err: any, result: SetEnqueueCreateFtpAccountResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueResizeFTPAccount(setEnqueueResizeFtpAccount: SetEnqueueResizeFtpAccount1, callback: (err: any, result: SetEnqueueResizeFtpAccountResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetReadNews(setReadNews: SetReadNews, callback: (err: any, result: SetReadNewsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetAddServerScheduledOperation(setAddServerScheduledOperation: SetAddServerScheduledOperation, callback: (err: any, result: SetAddServerScheduledOperationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetUpdateServerScheduledOperation(setUpdateServerScheduledOperation: SetUpdateServerScheduledOperation, callback: (err: any, result: SetUpdateServerScheduledOperationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRemoveServerScheduledOperation(setRemoveServerScheduledOperation: SetRemoveServerScheduledOperation, callback: (err: any, result: SetRemoveServerScheduledOperationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueuePurchaseSharedStorage(setEnqueuePurchaseSharedStorage: SetEnqueuePurchaseSharedStorage, callback: (err: any, result: SetEnqueuePurchaseSharedStorageResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueRemoveSharedStorage(setEnqueueRemoveSharedStorage: SetEnqueueRemoveSharedStorage, callback: (err: any, result: SetEnqueueRemoveSharedStorageResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueModifySharedStorage(setEnqueueModifySharedStorage: SetEnqueueModifySharedStorage, callback: (err: any, result: SetEnqueueModifySharedStorageResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueAddIQNSharedStorage(setEnqueueAddIqnSharedStorage: SetEnqueueAddIqnSharedStorage1, callback: (err: any, result: SetEnqueueAddIqnSharedStorageResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueRemoveIQNSharedStorage(setEnqueueRemoveIqnSharedStorage: SetEnqueueRemoveIqnSharedStorage1, callback: (err: any, result: SetEnqueueRemoveIqnSharedStorageResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRenameSharedStorage(setRenameSharedStorage: SetRenameSharedStorage, callback: (err: any, result: SetRenameSharedStorageResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetUpdatePersonalTemplate(setUpdatePersonalTemplate: SetUpdatePersonalTemplate, callback: (err: any, result: SetUpdatePersonalTemplateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetRemovePersonalTemplate(setRemovePersonalTemplate: SetRemovePersonalTemplate, callback: (err: any, result: SetRemovePersonalTemplateResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetPurchasedAdditionalServices(setPurchasedAdditionalServices: SetPurchasedAdditionalServices, callback: (err: any, result: SetPurchasedAdditionalServicesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetControlToolActive(setControlToolActive: SetControlToolActive, callback: (err: any, result: SetControlToolActiveResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetControlToolDisable(setControlToolDisable: SetControlToolDisable, callback: (err: any, result: SetControlToolDisableResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetControlToolCheck(getControlToolCheck: GetControlToolCheck, callback: (err: any, result: GetControlToolCheckResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetControlToolActivationRequests(getControlToolActivationRequests: GetControlToolActivationRequests, callback: (err: any, result: GetControlToolActivationRequestsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetControlToolActivationRequest(setControlToolActivationRequest: SetControlToolActivationRequest, callback: (err: any, result: SetControlToolActivationRequestResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetNetworkAdapterConfiguration(getNetworkAdapterConfiguration: GetNetworkAdapterConfiguration, callback: (err: any, result: GetNetworkAdapterConfigurationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetControlToolCommandResult(getControlToolCommandResult: GetControlToolCommandResult, callback: (err: any, result: GetControlToolCommandResultResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueUpdateControlTool(setEnqueueUpdateControlTool: SetEnqueueUpdateControlTool, callback: (err: any, result: SetEnqueueUpdateControlToolResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetScheduleOccurrences(getScheduleOccurrences: GetScheduleOccurrences, callback: (err: any, result: GetScheduleOccurrencesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetVDCGraph(getVdcGraph: GetVdcGraph1, callback: (err: any, result: GetVdcGraphResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetAddVDCGraph(setAddVdcGraph: SetAddVdcGraph1, callback: (err: any, result: SetAddVdcGraphResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetUpdateVDCGraph(setUpdateVdcGraph: SetUpdateVdcGraph1, callback: (err: any, result: SetUpdateVdcGraphResponse1, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAssistanceLanguages(getAssistanceLanguages: GetAssistanceLanguages, callback: (err: any, result: GetAssistanceLanguagesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAssistanceLanguagesList(getAssistanceLanguagesList: GetAssistanceLanguagesList, callback: (err: any, result: GetAssistanceLanguagesListResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetUpdateAssistanceRequest(setUpdateAssistanceRequest: SetUpdateAssistanceRequest, callback: (err: any, result: SetUpdateAssistanceRequestResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetAssistanceRequestDetails(getAssistanceRequestDetails: GetAssistanceRequestDetails, callback: (err: any, result: GetAssistanceRequestDetailsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetAssistanceQuotationAcceptance(setAssistanceQuotationAcceptance: SetAssistanceQuotationAcceptance, callback: (err: any, result: SetAssistanceQuotationAcceptanceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetSendAssistanceRequest(setSendAssistanceRequest: SetSendAssistanceRequest, callback: (err: any, result: SetSendAssistanceRequestResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetInsertAssistanceRequest(setInsertAssistanceRequest: SetInsertAssistanceRequest, callback: (err: any, result: SetInsertAssistanceRequestResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetUserAssistanceRequests(getUserAssistanceRequests: GetUserAssistanceRequests, callback: (err: any, result: GetUserAssistanceRequestsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueuePurchasePrivateCloud(setEnqueuePurchasePrivateCloud: SetEnqueuePurchasePrivateCloud, callback: (err: any, result: SetEnqueuePurchasePrivateCloudResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudResourcesTypes(getPrivateCloudResourcesTypes: GetPrivateCloudResourcesTypes, callback: (err: any, result: GetPrivateCloudResourcesTypesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudResourcesTypes2(getPrivateCloudResourcesTypes2: GetPrivateCloudResourcesTypes2, callback: (err: any, result: GetPrivateCloudResourcesTypes2Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedPrivateClouds(getPurchasedPrivateClouds: GetPurchasedPrivateClouds, callback: (err: any, result: GetPurchasedPrivateCloudsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedPrivateCloudDetails(getPurchasedPrivateCloudDetails: GetPurchasedPrivateCloudDetails, callback: (err: any, result: GetPurchasedPrivateCloudDetailsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPurchasedPrivateCloudDetails2(getPurchasedPrivateCloudDetails2: GetPurchasedPrivateCloudDetails2, callback: (err: any, result: GetPurchasedPrivateCloudDetails2Response, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueModifyPrivateCloudResources(setEnqueueModifyPrivateCloudResources: SetEnqueueModifyPrivateCloudResources, callback: (err: any, result: SetEnqueueModifyPrivateCloudResourcesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueuePrivateCloudDeletion(setEnqueuePrivateCloudDeletion: SetEnqueuePrivateCloudDeletion, callback: (err: any, result: SetEnqueuePrivateCloudDeletionResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CancelDeletePrivateCloudInstance(cancelDeletePrivateCloudInstance: CancelDeletePrivateCloudInstance, callback: (err: any, result: CancelDeletePrivateCloudInstanceResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueuePrivateCloudActivation(setEnqueuePrivateCloudActivation: SetEnqueuePrivateCloudActivation, callback: (err: any, result: SetEnqueuePrivateCloudActivationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudOrganizations(getPrivateCloudOrganizations: GetPrivateCloudOrganizations, callback: (err: any, result: GetPrivateCloudOrganizationsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetPrivateCloudOrganizationDetails(getPrivateCloudOrganizationDetails: GetPrivateCloudOrganizationDetails, callback: (err: any, result: GetPrivateCloudOrganizationDetailsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetHybridLinksbyOrg(getHybridLinksbyOrg: GetHybridLinksbyOrg, callback: (err: any, result: GetHybridLinksbyOrgResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetActivatedPrivateCloudFeatures(getActivatedPrivateCloudFeatures: GetActivatedPrivateCloudFeatures, callback: (err: any, result: GetActivatedPrivateCloudFeaturesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueModifyPrivateCloudOrganization(setEnqueueModifyPrivateCloudOrganization: SetEnqueueModifyPrivateCloudOrganization, callback: (err: any, result: SetEnqueueModifyPrivateCloudOrganizationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueLoadBalancerCreation(setEnqueueLoadBalancerCreation: SetEnqueueLoadBalancerCreation, callback: (err: any, result: SetEnqueueLoadBalancerCreationResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SetEnqueueLoadBalancerDeletion(setEnqueueLoadBalancerDeletion: SetEnqueueLoadBalancerDeletion, callback: (err: any, result: SetEnqueueLoadBalancerDeletionResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetLoadBalancers(getLoadBalancers: GetLoadBalancers, callback: (err: any, result: GetLoadBalancersResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
}
